### ISSUE TITLE
rich.errors.LiveError: Only one live display may be active at once

### ISSUE THREAD

**Issue by meme-lord** [semgrep/semgrep#10562]
**Describe the bug**
When attempting to run a scan with the community ruleset I get the error "rich.errors.LiveError: Only one live display may be active at once"

**To Reproduce**
```sh
mkdir /tmp/test
cd /tmp/test
git clone https://github.com/semgrep/semgrep-rules.git
mkdir empty
cd empty/
SEMGREP_RULES=/tmp/test/semgrep-rules/ semgrep scan . --debug
```
Output:
```
┌──── ○○○ ────┐
│ Semgrep CLI │
└─────────────┘

semgrep version 1.90.0
Failed to get project url from 'git ls-remote': Command failed with exit code: 128
-----
Command failed with output:
fatal: No remote configured to list refs from.


Failed to run 'git ls-remote --get-url'. Possible reasons:

- the git binary is not available
- the current working directory is not a git repository
- the current working directory is not marked as safe
    (fix with `git config --global --add safe.directory $(pwd)`)

Try running the command yourself to debug the issue.
⠋ Loading rules...Loading local config from /tmp/rep/semgrep-rules
Done loading local config from /tmp/rep/semgrep-rules
⠋ Loading rules...                                                                                                  Only one live display may be active at once
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/commands/wrapper.py", line 37, in wrapper
    func(*args, **kwargs)
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/commands/scan.py", line 802, in scan
    ) = semgrep.run_scan.run_scan(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/tracing.py", line 101, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/run_scan.py", line 483, in run_scan
    configs_obj, config_errors = get_config(
                                 ^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/tracing.py", line 101, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/config_resolver.py", line 988, in get_config
    config, errors = Config.from_config_list(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/tracing.py", line 101, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/config_resolver.py", line 586, in from_config_list
    resolved_config, config_errors = resolve_config(
                                     ^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/tracing.py", line 101, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/config_resolver.py", line 495, in resolve_config
    config, errors = parse_config_files(
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/tracing.py", line 101, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/semgrep/config_resolver.py", line 436, in parse_config_files
    for config_id, contents, config_path in progress.track(
                                            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/rich/progress.py", line 167, in track
    with progress:
         ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/rich/progress.py", line 1168, in __enter__
    self.start()
  File "/usr/lib/python3.12/site-packages/rich/progress.py", line 1159, in start
    self.live.start(refresh=True)
  File "/usr/lib/python3.12/site-packages/rich/live.py", line 113, in start
    self.console.set_live(self)
  File "/usr/lib/python3.12/site-packages/rich/console.py", line 836, in set_live
    raise errors.LiveError("Only one live display may be active at once")
rich.errors.LiveError: Only one live display may be active at once
Not sending pseudonymous metrics since metrics are configured to OFF and registry usage is False
```

I deleted folders from the rules to see if I could narrow it down.
It still works when these folders remain:
```
csharp  elixir  kotlin  ocaml  solidity  terraform
```
but if I remove any one of them no error occurs.

**Expected behavior**
Starts scanning without throwing this error

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
Run semgrep rulesets

**Comment by meme-lord** [comment]
And my rich module version from `pip freeze` is 13.5.3

**Comment by meme-lord** [comment]
It works when I downgrade semgrep to version 1.86.0 but occurs on 1.87.0

**Comment by Sjord** [comment]
[feat(ux): Add Loading indicator during CLI startup (semgrep/semgrep-p… · semgrep/semgrep@e04e742](https://github.com/semgrep/semgrep/commit/e04e74284fd222a9a1f383abd8509b109fb94e72)

That change adds a progress bar and calls [semgrep.config_resolver.get_config](https://github.com/semgrep/semgrep/blob/develop/cli/src/semgrep/config_resolver.py#L988), which calls [from_config_list](https://github.com/semgrep/semgrep/blob/develop/cli/src/semgrep/config_resolver.py#L586), [resolve_config](https://github.com/semgrep/semgrep/blob/develop/cli/src/semgrep/config_resolver.py#L495), [parse_config_files](https://github.com/semgrep/semgrep/blob/develop/cli/src/semgrep/config_resolver.py#L436-L443), which attempts to show its own progress bar when there are more than 500 config files. Showing a progress bar while showing a progress bar raises an exception.

**Comment by kopecs** [comment]
cc: @zzeleznick

**Comment by Sjord** [comment]
According to the [1.9.1 release notes](https://github.com/semgrep/semgrep/releases/tag/v1.91.0), this bug is fixed.

**Comment by Sjord** [comment]
[fix(oss): Address python \`rich.errors.LiveError\` where multiple progr… · semgrep/semgrep@154427f](https://github.com/semgrep/semgrep/commit/154427fbcf9663de1878c0544efdf2624966b311)
