### ISSUE TITLE
Semgrep core exceptions UnicodeDecode error

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#1244]
**Describe the bug**
Is encoding handled correctly in semgrep?

I am using semgrep APIs with libsast.
Integration code.

```
# -*- coding: utf_8 -*-
"""Semantic Grep Helpers."""
import multiprocessing
from io import StringIO
import json


from semgrep.constants import OutputFormat
from semgrep.output import (
    OutputHandler,
    OutputSettings,
)
from semgrep import semgrep_main

try:
    CPU_COUNT = multiprocessing.cpu_count()
except NotImplementedError:
    CPU_COUNT = 1  # CPU count is not implemented on Windows


def invoke_semgrep(paths, scan_rules, **kwargs):
    """Call Semgrep."""
    io_capture = StringIO()
    output_handler = OutputHandler(
        OutputSettings(
            output_format=OutputFormat.JSON,
            output_destination=None,
            quiet=False,
            error_on_findings=False,
            strict=False,
        ),
        stdout=io_capture,
    )
    semgrep_main.main(
        output_handler=output_handler,
        target=[pt.as_posix() for pt in paths],
        jobs=CPU_COUNT,
        pattern=None,
        lang=None,
        config=scan_rules,
        **kwargs,
    )
    output_handler.close()
    return json.loads(io_capture.getvalue())

```
While running tests, when binary files in`__pycache__/` are read by semgrep, it triggers UnicodeError.

```
libsast/scanner.py:57: in scan
    self.options).scan(valid_paths)
libsast/core_sgrep/semantic_sgrep.py:36: in scan
    sgrep_out = invoke_semgrep(paths, self.scan_rules)
libsast/core_sgrep/helpers.py:41: in invoke_semgrep
    **kwargs,
venv/lib/python3.7/site-packages/semgrep/semgrep_main.py:343: in main
    semgrep_errors = [e.into_semgrep_error() for e in semgrep_core_errors]
venv/lib/python3.7/site-packages/semgrep/semgrep_main.py:343: in <listcomp>
    semgrep_errors = [e.into_semgrep_error() for e in semgrep_core_errors]
venv/lib/python3.7/site-packages/semgrep/core_exception.py:70: in into_semgrep_error
    file_hash = SourceTracker.add_source(f.read())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.utf_8.IncrementalDecoder object at 0x10a58f590>
input = b'B\r\r\n\xdfZ\xc8^.\x00\x00\x00\xe3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00@\x00\x00\x00s2\x0.../libsast/tests/unit/assets/files/test_file.py\xda\x08<module>\x01\x00\x00\x00s\x06\x00\x00\x00\x08\x00\x12\x00\x08\x02'
final = True

    def decode(self, input, final=False):
        # decode input (taking the buffer into account)
        data = self.buffer + input
>       (result, consumed) = self._buffer_decode(data, self.errors, final)
E       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 4: invalid continuation byte

../../.pyenv/versions/3.7.7/lib/python3.7/codecs.py:322: UnicodeDecodeError
----------------------------- Captured stderr call -----------------------------
running 1 rules...
=========================== short test summary info ============================
FAILED tests/unit/test_semgrep.py::test_semgrep - UnicodeDecodeError: 'utf-8'...
```

```
$ libsast -s tests/unit/assets/rules/semantic_grep/ tests/unit/assets/files/__pycache__/
running 1 rules...
Traceback (most recent call last):
  File "/xxx/Code/libsast/venv/bin/libsast", line 11, in <module>
    load_entry_point('libsast', 'console_scripts', 'libsast')()
  File "/xxx/Code/libsast/libsast/__main__.py", line 97, in main
    result = Scanner(options, args.path).scan()
  File "/xxx/Code/libsast/libsast/scanner.py", line 57, in scan
    self.options).scan(valid_paths)
  File "/xxx/Code/libsast/libsast/core_sgrep/semantic_sgrep.py", line 36, in scan
    sgrep_out = invoke_semgrep(paths, self.scan_rules)
  File "/xxx/Code/libsast/libsast/core_sgrep/helpers.py", line 41, in invoke_semgrep
    **kwargs,
  File "/xxx/Code/libsast/venv/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 343, in main
    semgrep_errors = [e.into_semgrep_error() for e in semgrep_core_errors]
  File "/xxx/Code/libsast/venv/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 343, in <listcomp>
    semgrep_errors = [e.into_semgrep_error() for e in semgrep_core_errors]
  File "/xxx/Code/libsast/venv/lib/python3.7/site-packages/semgrep/core_exception.py", line 70, in into_semgrep_error
    file_hash = SourceTracker.add_source(f.read())
  File "/xxx/.pyenv/versions/3.7.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 4: invalid continuation byte
```

However, semgrep handles this gracefully.

```
$ semgrep -f tests/unit/assets/rules/semantic_grep/ tests/unit/assets/files/__pycache__/
running 1 rules...
```

Any ideas about what might be happening?

**Comment by ajinabraham** [comment]
Looks like this is fixed
