### ISSUE TITLE
UnicodeDecodeError crash when scanning binary files

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#1247]
**Describe the bug**

I believe this is just a regression causing #563 again.

```
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 33, in <module>
    sys.exit(load_entry_point('semgrep==0.14.0', 'console_scripts', 'semgrep')())
  File "/usr/local/Cellar/semgrep/0.14.0/libexec/lib/python3.8/site-packages/semgrep/__main__.py", line 11, in main
    cli()
  File "/usr/local/Cellar/semgrep/0.14.0/libexec/lib/python3.8/site-packages/semgrep/cli.py", line 323, in cli
    semgrep.semgrep_main.main(
  File "/usr/local/Cellar/semgrep/0.14.0/libexec/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 343, in main
    semgrep_errors = [e.into_semgrep_error() for e in semgrep_core_errors]
  File "/usr/local/Cellar/semgrep/0.14.0/libexec/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 343, in <listcomp>
    semgrep_errors = [e.into_semgrep_error() for e in semgrep_core_errors]
  File "/usr/local/Cellar/semgrep/0.14.0/libexec/lib/python3.8/site-packages/semgrep/core_exception.py", line 70, in into_semgrep_error
    file_hash = SourceTracker.add_source(f.read())
  File "/usr/local/Cellar/semgrep/0.14.0/libexec/bin/../lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**To Reproduce**

```sh
curl https://placekitten.com/100/100 > /tmp/cat.jpg
semgrep -l py -e 0 /tmp/cat.jpg
```

**Expected behavior**

Semgrep probably shouldn't crash. Maybe a parse error is acceptable. But I think it's pretty common to have binary files (icons, logos, etc.) alongside your code and it's kind of a chore to explicitly ignore them.

Since this is the second time we have this bug, we should probably add an E2E test case, as well.

**Environment**

0.14.0

**Comment by ajinabraham** [comment]
Related to https://github.com/returntocorp/semgrep/issues/1244 ?

**Comment by underyx** [comment]
@ajinabraham I think so! I'm not 100% sure on what the behavior is here, but it seems that semgrep only crashes when you target an unparseable file, such as a binary, by name. You don't see a failure in your issue on the CLI because you're running on a directory and semgrep is somehow ignoring the unparseable files.

The https://github.com/returntocorp/semgrep/pull/1250 PR should change it so you get a parse error back, instead of seeing a crash.
