### ISSUE TITLE
Semgrep 0.21.0 error on installing in a ubuntu docker container

### ISSUE THREAD

**Issue by SPoint42** [semgrep/semgrep#1596]
**Describe the bug**
I try to install semgrep in a ubuntu dockerized because need to add it with other tools. 

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

**Extract of the build error**
Successfully built bs4 gitlab
Installing collected packages: certifi, idna, chardet, urllib3, requests, soupsieve, beautifulsoup4, bs4, gitlab
Successfully installed beautifulsoup4-4.9.1 bs4-0.0.1 certifi-2020.6.20 chardet-3.0.4 gitlab-1.0.2 idna-2.10 requests-2.24.0 soupsieve-2.0.1 urllib3-1.25.10
Removing intermediate container f2c280e7c21b
 ---> 81602be9e1a0
Step 9/16 : RUN /bin/bash /var/usr/semgrep-install.sh
 ---> Running in 6b2202ee10ab
Installing tarball from https://github.com/returntocorp/semgrep/releases/download/v0.21.0/semgrep-v0.21.0-ubuntu-16.04.tgz (checksum: https://github.com/returntocorp/semgrep/releases/download/v0.21.0/semgrep-v0.21.0-ubuntu-16.04.tgz
.sha256)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   658  100   658    0     0   2521      0 --:--:-- --:--:-- --:--:--  2530
100 47.0M  100 47.0M    0     0  8505k      0  0:00:05  0:00:05 --:--:-- 10.9M
semgrep-v0.21.0-ubuntu-16.04.tgz: OK
Traceback (most recent call last):
  File "/usr/local/lib/semgrep-files/__main__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/semgrep-files/semgrep/cli.py", line 7, in <module semgrep.cli>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/semgrep-files/semgrep/config_resolver.py", line 19, in <module semgrep.config_resolver>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/semgrep-files/semgrep/error.py", line 13, in <module semgrep.error>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/semgrep-files/semgrep/rule_lang.py", line 18, in <module semgrep.rule_lang>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/semgrep-files/jsonschema/__init__.py", line 22, in <module jsonschema>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/semgrep-files/jsonschema/validators.py", line 446, in <module jsonschema.validators>
  File "/usr/local/lib/semgrep-files/jsonschema/_utils.py", line 54, in load_schema
  File "/usr/local/lib/semgrep-files/pkgutil.py", line 637, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/semgrep-files/jsonschema/schemas/draft3.json'
Semgrep installed! Version: 

**Environment**
local build on a docker ubuntu

**Comment by SPoint42** [comment]
this work on 0.20, and 0.19

**Comment by brendongo** [comment]
Hi @SPoint42 looks like our nuitka binary had problems including the jsonschema file.

Is there a reason you aren't using `pip3 install semgrep==0.21.0`?

**Comment by SPoint42** [comment]
> `pip3 install semgrep==0.21.0`?

It was not working last week. Don't know why .....
