### ISSUE TITLE
Semgrep output not parsable as JSON

### ISSUE THREAD

**Issue by chmccreery** [semgrep/semgrep#1630]
**Describe the bug**
Instead of returning to out a json string and to err an empty string, out is an empty string and err is plain text

**To Reproduce**
https://semgrep.dev/s/rZDn/

Output to err: 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/semgrep/rule_lang.py", line 408, in validate_yaml
    jsonschema.validate(data.unroll(), RuleSchema.get(), cls=Draft7Validator)
  File "/usr/local/lib/python3.8/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'patterns' is a required property
Failed validating 'required' in schema[0]:
    {'additionalProperties': False,
     'properties': {'patterns': {'$ref': '#/definitions/patterns-content'}},
     'required': ['patterns'],
     'type': 'object'}
On instance:
    {'metavariable-regex': {'metavariable': '$HOST', 'regex': '(?i)...'}}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/semgrep/rule_lang.py", line 286, in __getitem__
    return next(v for k, v in self._internal.items() if k.value == key)
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/local/lib/python3.8/site-packages/semgrep/cli.py", line 355, in cli
    semgrep.semgrep_main.main(
  File "/usr/local/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 271, in main
    valid_configs, config_errors = get_config(pattern, lang, config)
  File "/usr/local/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 132, in get_config
    configs = semgrep.config_resolver.resolve_config(config)
  File "/usr/local/lib/python3.8/site-packages/semgrep/config_resolver.py", line 248, in resolve_config
    config = load_config_from_local_path(config_str)
  File "/usr/local/lib/python3.8/site-packages/semgrep/config_resolver.py", line 167, in load_config_from_local_path
    return parse_config_at_path(loc)
  File "/usr/local/lib/python3.8/site-packages/semgrep/config_resolver.py", line 109, in parse_config_at_path
    return parse_config_string(config_id, f.read(), str(loc))
  File "/usr/local/lib/python3.8/site-packages/semgrep/config_resolver.py", line 116, in parse_config_string
    data = parse_yaml_preserve_spans(contents, filename)
  File "/usr/local/lib/python3.8/site-packages/semgrep/rule_lang.py", line 360, in parse_yaml_preserve_spans
    validate_yaml(data)
  File "/usr/local/lib/python3.8/site-packages/semgrep/rule_lang.py", line 413, in validate_yaml
    item = item.value[el]
  File "/usr/local/lib/python3.8/site-packages/semgrep/rule_lang.py", line 288, in __getitem__
    raise KeyError(key)
KeyError: 'pattern-either'`

If the severity: WARNING line is removed, the error is handled correctly, so probably has to do with that control flow.

**Expected behavior**
Error is handled like by printing something like the following to stdout: '{"results": [], "errors": [{"type": "InvalidRuleSchemaError", "code": 4, "short_msg": "Invalid rule schema", "long_msg": "At least one of the following required properties is missing: 'pattern', 'pattern-either', 'pattern-regex', 'patterns'", "level": "error", "spans": [{"start": {"line": 1, "col": 1}, "end": {"line": 6, "col": 1}, "source_hash": "a46e589472e9e0f9467c9ab5568f1ddde864c9a4080b1d2ff19a03fc45b51151", "file": ".sgrep.yml", "context_start": null, "context_end": null}]}, {"type": "SemgrepError", "code": 7, "message": "run with --strict and there were 1 errors loading configs"}]}\n'

**Screenshots**

**Environment**
Using Semgrep 0.21, docker or pip installed version both lead to error

**Comment by chmccreery** [comment]
<img width="553" alt="Screen Shot 2020-09-02 at 3 55 11 PM" src="https://user-images.githubusercontent.com/25408780/92045175-c2c51680-ed34-11ea-90b0-256b8e8cd0fb.png">

**Comment by chmccreery** [comment]
Also see https://github.com/returntocorp/semgrep-app/issues/500

**Comment by aryx** [comment]
Also, can we actually see the error in the editor? Right now it just says "unspecified error", but
I have no idea how to know what the error is. Can we add a flag in Tools to be more verbose about errors?

**Comment by aryx** [comment]
I think the situation is better now that we have semgrep ocaml rules to check  for the wrong use of printing function.
