### ISSUE TITLE
Error when trying to run semgrep that installed with python

### ISSUE THREAD

**Issue by omerlh** [semgrep/semgrep#1949]
**Describe the bug**
When installing semgrep via pip, I am getting the following error:

semgrep --debug views/
running 1 rules from 1 config .semgrep.yml 
running 1 rules...
Running rule find-missing-sri...
spacegrep output could not be parsed as JSON.
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/semgrep/cli.py", line 378, in cli
    semgrep.semgrep_main.main(
  File "/usr/local/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 223, in main
    rule_matches_by_rule, debug_steps_by_rule, semgrep_errors, num_targets = CoreRunner(
  File "/usr/local/lib/python3.9/site-packages/semgrep/core_runner.py", line 531, in invoke_semgrep
    findings_by_rule, debug_steps_by_rule, errors, num_targets = self._run_rules(
  File "/usr/local/lib/python3.9/site-packages/semgrep/core_runner.py", line 499, in _run_rules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(
  File "/usr/local/lib/python3.9/site-packages/semgrep/core_runner.py", line 390, in _run_rule
    output_json = run_spacegrep(patterns, targets)
  File "/usr/local/lib/python3.9/site-packages/semgrep/spacegrep.py", line 49, in run_spacegrep
    errors.extend(output_json["errors"])
KeyError: 'errors'

The same config file with the same source files and same semgrep version is working is expected when semgrep is installed with brew or running inside a container

**Comment by aryx** [comment]
@mjambon ? "spacegrep output could not be parsed as JSON."

**Comment by mjambon** [comment]
This was a packaging bug, sorry about that. This will be fixed in the next release of semgrep (0.31.0) which should happen next week.
