### ISSUE TITLE
indefinite hang when running r/javascript rule

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1981]
**Describe the bug**

Semgrep hangs for 20+ minutes when running r/javascript on itself. The first rule is `javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector`.

**To Reproduce**

```
ine@imbp4 ~/D/r/semgrep (ie/fix-help) [130]> time semgrep --config="r/javascript"
using config from https://semgrep.dev/r/javascript. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 124 rules...
  0%|                                                                                                                                                                        |0/124  0%|                                                                                                                                                                        |0/124
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 33, in <module>
    sys.exit(load_entry_point('semgrep==0.30.0', 'console_scripts', 'semgrep')())
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/cli.py", line 378, in cli
    semgrep.semgrep_main.main(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 223, in main
    rule_matches_by_rule, debug_steps_by_rule, semgrep_errors, num_targets = CoreRunner(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/core_runner.py", line 531, in invoke_semgrep
    findings_by_rule, debug_steps_by_rule, errors, num_targets = self._run_rules(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/core_runner.py", line 499, in _run_rules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/core_runner.py", line 424, in _run_rule
    findings_for_rule, debugging_steps = evaluate(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 362, in evaluate
    valid_ranges_to_output = evaluate_expression(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 422, in evaluate_expression
    return _evaluate_expression(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 463, in _evaluate_expression
    remainining_ranges = _evaluate_expression(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 449, in _evaluate_expression
    evaluated_ranges = [
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 450, in <listcomp>
    _evaluate_expression(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 463, in _evaluate_expression
    remainining_ranges = _evaluate_expression(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 449, in _evaluate_expression
    evaluated_ranges = [
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 450, in <listcomp>
    _evaluate_expression(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 484, in _evaluate_expression
    ranges_left = _evaluate_single_expression(
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/evaluation.py", line 201, in _evaluate_single_expression
    is_enclosed = keep_inside_this_range.is_enclosing_or_eq(arange)
  File "/usr/local/Cellar/semgrep/0.30.0/libexec/lib/python3.9/site-packages/semgrep/semgrep_types.py", line 118, in is_enclosing_or_eq
    def is_enclosing_or_eq(self, other_range: "Range") -> bool:
KeyboardInterrupt

________________________________________________________
Executed in   22.89 mins   fish           external
```

**Expected behavior**
Execution should finish in <60sec for the whole rule pack.

**What is the priority of the bug to you?**
P1 for me but could be P0 for user so tagging as high.

**Environment**
```
$ semgrep --version
0.30.0
```

**Comment by TeoZosa** [comment]
+1, I think this same issue is causing CI job failures on my end with `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` errors. 

Failures started this morning at 9:31 AM PST (last successful run at 8:27 AM PST).

**Comment by mschwager** [comment]
Looks like this is from running the [`jquery-insecure-selector`](https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/jquery/security/audit/jquery-insecure-selector.yaml) rule against the `semgrep-core/tests/OTHER/PERF/swagger-ui-bundle.js` file in this repository. I can reproduce the hanging behavior in `semgrep-core` by running the appropriate rules file ([rules-file.txt](https://github.com/returntocorp/semgrep/files/5518383/rules-file.txt)) against `swagger-ui-bundle.js`:

```
$ semgrep-core -lang javascript -rules_file /tmp/rules-file.txt -j 8 -use_parsing_cache /tmp/cache -timeout 0 -max_memory 0 semgrep-core/tests/OTHER/PERF/swagger-ui-bundle.js
...
<HANGS>
```

I'm going to include this on the program analysis board.

**Comment by mjambon** [comment]
The following rule takes 28 minutes on my machine, and returns 0 matches:
```yaml
- id: 0..0.0.4.4.0.0.3
  pattern: |
    function (...,$Z,...) {
      ...
      $Y = <... $Z ...>;
      ...
    }
  severity: WARNING
  languages:
  - javascript
  message: <internalonly>
```

Is this task about making pattern matching faster or about setting a timeout?

A timeout for parsing+matching can be set with `semgrep-core -timeout 5` and it works, but optimizing pattern matching so that it completes within 5 seconds on this test case is whole different story.

**Comment by brendongo** [comment]
Verified 0.32.0 doesn't stall with new timeouts

**Comment by ievans** [comment]
@brendongo @mjambon we should open a new issue to track the poor matching speed
