### ISSUE TITLE
Cannot Run Semgrep - Exception: Could not locate 'semgrep-core' binary

### ISSUE THREAD

**Issue by aantn** [semgrep/semgrep#2313]
I installed semgrep using pip. When I run the command `semgrep` then I recieve the following error:

```
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\semgrep.exe\__main__.py", line 4, in <module>
  File "c:\python39\lib\site-packages\semgrep\__main__.py", line 5, in <module>
    from semgrep.cli import cli
  File "c:\python39\lib\site-packages\semgrep\cli.py", line 7, in <module>
    import semgrep.config_resolver
  File "c:\python39\lib\site-packages\semgrep\config_resolver.py", line 13, in <module>
    from semgrep.constants import DEFAULT_CONFIG_FILE
  File "c:\python39\lib\site-packages\semgrep\constants.py", line 29, in <module>
    SEMGREP_PATH = compute_semgrep_path()
  File "c:\python39\lib\site-packages\semgrep\util.py", line 162, in compute_semgrep_path
    return compute_executable_path("semgrep-core")
  File "c:\python39\lib\site-packages\semgrep\util.py", line 157, in compute_executable_path
    raise Exception(f"Could not locate '{exec_name}' binary")
Exception: Could not locate 'semgrep-core' binary
```

**Comment by aantn** [comment]
The issue seems to be that semgrep is looking for semgrep-core in C:\Python39 but it should actually look in C:\Python39\Scripts

**Comment by ievans** [comment]
Hi @aantn, thanks for this issue (I'm the same person who just replied to your email!) -- could you add a bit of detail about the environment you are running under? This looks like Windows -- what version, and is it under [WSL](https://docs.microsoft.com/en-us/windows/wsl/about)? I believe Semgrep is currently only supported on Windows running under the WSL, @mschwager can confirm when he returns from holiday break.

Also, what is the priority of the issue for you? Is it a blocker to using Semgrep further?

**Comment by aantn** [comment]
Yes, that's right. I'm was running it directly on Windows before I realized
that it isn't supported.

This specific error has an easy fix but there are other issues running it
on Windows once you fix this issue. I may take a deeper look at this later
on as for me usecase I need native window support.

You can close this issue.

**Comment by ievans** [comment]
Thanks @aantn! I'm going to close for now, but cc @mschwager / @pabloest / @dlukeomalley this is probably a sign that our documentation should be more conspicuous about "works under WSL but _not_ Windows"
