### ISSUE TITLE
PermissionError exception not handled

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#2346]
**Describe the bug**
Semgrep fails with an exception when it does not have permissions to run on files.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

```
wget https://registry.npmjs.org/webpack/-/webpack-0.1.0.tgz
tar -xvf webpack-0.1.0.tgz
semgrep --config p/r2c-ci webpack
```

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/target_manager.py", line 129, in _expand_dir
    tracked_output = sub_check_output(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/util.py", line 143, in sub_check_output
    result = subprocess.check_output(cmd, **kwargs)  # nosem: python.lang.security.audit.dangerous-subprocess-use.dangerous-subprocess-use
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'ls-files', '*.js']' returned non-zero exit status 128



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/cli.py", line 430, in cli
    semgrep.semgrep_main.main(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 242, in main
    ) = CoreRunner(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/core_runner.py", line 547, in invoke_semgrep
    findings_by_rule, debug_steps_by_rule, errors, all_targets = self._run_rules(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/core_runner.py", line 507, in _run_rules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/core_runner.py", line 337, in _run_rule
    targets = self.get_files_for_language(language, rule, target_manager)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/core_runner.py", line 477, in get_files_for_language
    targets = target_manager.get_files(language, rule.includes, rule.excludes)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/target_manager.py", line 281, in get_files
    targets = self.filtered_files(lang)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/target_manager.py", line 244, in filtered_files
    targets = self.expand_targets(directories, lang, self.respect_git_ignore)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/target_manager.py", line 188, in expand_targets
    TargetManager._expand_dir(target, lang, respect_git_ignore)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/target_manager.py", line 158, in _expand_dir
    ext_files = _find_files_with_extention(curr_dir, ext)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/target_manager.py", line 116, in _find_files_with_extention
    return {
  File "/home/ubuntu/.local/lib/python3.8/site-packages/semgrep/target_manager.py", line 119, in <setcomp>
    if p.is_file() and TargetManager._is_valid(p)
  File "/usr/lib/python3.8/pathlib.py", line 1420, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/lib/python3.8/pathlib.py", line 1194, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: 'package/test/resolve_test.js'
```

**Expected behavior**

Like grep, semgrep should note the error and continue. Should probably show up as a key under `errors` in the JSON output.

```
ubuntu@ip-172-31-12-20:/tmp/isaac$ grep -R  "foo" .
grep: ./package/test/browsertest: Permission denied
grep: ./package/test/resolve_test.js: Permission denied
grep: ./package/test/buildDeps_test.js: Permission denied
grep: ./package/test/fixtures: Permission denied
grep: ./package/lib/webpack.js: Permission denied
grep: ./package/lib/templateAsync.js: Permission denied
grep: ./package/lib/parse.js: Permission denied
grep: ./package/lib/templateSingle.js: Permission denied
grep: ./package/lib/writeChunk.js: Permission denied
grep: ./package/lib/writeSource.js: Permission denied
grep: ./package/lib/resolve.js: Permission denied
grep: ./package/lib/buildDeps.js: Permission denied
grep: ./package/examples/code-splitted-require.context: Permission denied
grep: ./package/examples/code-splitting: Permission denied
grep: ./package/examples/require.context: Permission denied
grep: ./package/bin/webpack.js: Permission denied
2 ubuntu@ip-172-31-12-20:/tmp/isaac$
```

**What is the priority of the bug to you?**
Probably P1

**Environment**
semgrep v0.35 on Ubuntu

**Comment by aryx** [comment]
related: https://github.com/returntocorp/semgrep/issues/2043
