### ISSUE TITLE
UnicodeDecodeError while running semgrep on strapi github repo

### ISSUE THREAD

**Issue by paresh-borkar** [semgrep/semgrep#2462]
**Describe the bug**
Ran into UnicodeDecodeError while running semgrep on strapi github repo. Semgrep version is 0.33.0

Please see details below:
/usr/local/bin/semgrep  -v --json --config=p/r2c-security-audit /home/tw/repos/strapi
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
using config from https://semgrep.dev/p/r2c-security-audit. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 202 rules...
 45%|#######################################6                                                |91/202
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/semgrep/cli.py", line 431, in cli
    severity=args.severity,
  File "/usr/local/lib/python3.6/dist-packages/semgrep/semgrep_main.py", line 242, in main
    ).invoke_semgrep(target_manager, filtered_rules)
  File "/usr/local/lib/python3.6/dist-packages/semgrep/core_runner.py", line 537, in invoke_semgrep
    rules, target_manager
  File "/usr/local/lib/python3.6/dist-packages/semgrep/core_runner.py", line 505, in _run_rules
    rule, target_manager, semgrep_core_ast_cache_dir, max_timeout_files
  File "/usr/local/lib/python3.6/dist-packages/semgrep/core_runner.py", line 430, in _run_rule
    rule, pattern_matches, self._allow_exec
  File "/usr/local/lib/python3.6/dist-packages/semgrep/evaluation.py", line 378, in evaluate
    message = interpolate_message_metavariables(rule, pattern_match)
  File "/usr/local/lib/python3.6/dist-packages/semgrep/evaluation.py", line 398, in interpolate_message_metavariables
    metavar, pattern_match.get_metavariable_value(metavar)
  File "/usr/local/lib/python3.6/dist-packages/semgrep/pattern_match.py", line 80, in get_metavariable_value
    value = file.read(length)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 1171: ordinal not in range(128)

**To Reproduce**
1. Clone the github repo for strapi using below command:
git clone https://github.com/strapi/strapi.git
2. Run the semgrep command as below:
/usr/local/bin/semgrep  -q --json --config=p/r2c-security-audit /home/tw/repos/strapi

**Expected behavior**
Expected the semgrep run to complete successfully and report any findings.

**What is the priority of the bug to you?**
This is blocking adoption of semgrep.

**Environment**
Installed semgrep version 0.33.0 using "pip3 install semgrep" command. Running python version 3.6.5 on "Ubuntu 18.04 LTS"

**Comment by brendongo** [comment]
Possible this is related to https://github.com/returntocorp/semgrep/issues/2111

Trying latest semgrep 0.38.0 seems to run on strapi with no issues.

**Comment by brendongo** [comment]
Closing as fixed. Feel free to open if upgrading to 0.38.0 did not fix the issue for you

**Comment by paresh-borkar** [comment]
Thanks @brendongo. Upgrading to 0.38.0 helped resolve the issue.
