### ISSUE TITLE
Got a error "TypeError: attrs() got an unexpected keyword argument 'eq'" when running at the first time after installing

### ISSUE THREAD

**Issue by tuhaolam** [semgrep/semgrep#2568]
**Describe the bug**
Got a error "TypeError: attrs() got an unexpected keyword argument 'eq'" when running at the first time after pip installment

**To Reproduce**
ζ semgrep -h
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 5, in <module>
    from semgrep.__main__ import main
  File "/usr/local/lib/python3.7/dist-packages/semgrep/__main__.py", line 5, in <module>
    from semgrep.cli import cli
  File "/usr/local/lib/python3.7/dist-packages/semgrep/cli.py", line 7, in <module>
    import semgrep.config_resolver
  File "/usr/local/lib/python3.7/dist-packages/semgrep/config_resolver.py", line 22, in <module>
    from semgrep.error import InvalidRuleSchemaError
  File "/usr/local/lib/python3.7/dist-packages/semgrep/error.py", line 103, in <module>
    @attr.s(auto_attribs=True, eq=True, frozen=True)
TypeError: attrs() got an unexpected keyword argument 'eq'

**Expected behavior**
To find the reason and fix it.

**Screenshots**

**What is the priority of the bug to you?**
P0

**Environment**
python3.7
Linux  4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 GNU/Linux

**Comment by tuhaolam** [comment]
ζ python3
Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45)
[GCC 9.2.1 20190909] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import attr
>>> attr.__version__
'19.1.0'

**Comment by tuhaolam** [comment]
After update attrs to attrs-20.3.0(>=19.3.0), it is fixed.
