### ISSUE TITLE
Issue with ellipsis matching introduced in version v0.41.0

### ISSUE THREAD

**Issue by robinjmurphy** [semgrep/semgrep#2646]
**Describe the bug**

The tests for one of our semgrep rules have started failing since version v0.41.0 was released.

**To Reproduce**

Rule and tests code here: https://semgrep.dev/s/5QR0/

Running this against v0.40.0 (as is the current version in the playground at time of writing) works fine.

However, running with the v0.41.0 release (and v0.41.1):

```
❯ docker run --rm -v "${PWD}:/src" returntocorp/semgrep:6c8281bafe839bff9266397176b1658099b785d2 --quiet --test .
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/semgrep/cli.py", line 411, in cli
    semgrep.test.test_main(args)
  File "/usr/local/lib/python3.9/site-packages/semgrep/test.py", line 432, in test_main
    generate_file_pairs(
  File "/usr/local/lib/python3.9/site-packages/semgrep/test.py", line 318, in generate_file_pairs
    tested = {
  File "/usr/local/lib/python3.9/site-packages/semgrep/test.py", line 319, in <dictcomp>
    filename: score_output_json(
  File "/usr/local/lib/python3.9/site-packages/semgrep/test.py", line 203, in score_output_json
    raise Exception(
Exception: found results on ok'ed lines - lines={27} path=/src/wrongerrcheck/wrong-err-check.go
```

**Expected behavior**

The statement on line 27 should be fine. However, it is failing. It looks like this `pattern-not` is broken:

```yaml
    - pattern-not: |
        if $ERR_B, ... = <...$F(...)...>; $ERR_B != nil {
          ...
        }
```

Interestingly, if the second variable is changed from an underscore `_` to a 3 character variable name the rule works 🤔

i.e.

```go
	// ok:wrong-err-check
	if err, foo := something3(); err != nil {
		return
	}
```

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

P1

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

Docker. Also Python in CI.

I wonder if this bug was introduced in #2618?

**Comment by mjambon** [comment]
@aryx It could well be a bug with caching, which was introduced a couple weeks ago. To check if it works without the caching optimization, pass `-no_opt_cache` to `semgrep-core`. This can be done by setting the environment variable `SEMGREP_CORE_EXTRA`:
```
SEMGREP_CORE_EXTRA="-no_opt_cache" semgrep <usual arguments>
```

**Comment by robinjmurphy** [comment]
Hmm it still seems to be broken with that environment variable:

```
❯ docker run --rm -v "${PWD}:/src" -e SEMGREP_CORE_EXTRA="-no_opt_cache" returntocorp/semgrep --quiet --test .
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/semgrep/cli.py", line 411, in cli
    semgrep.test.test_main(args)
  File "/usr/local/lib/python3.9/site-packages/semgrep/test.py", line 432, in test_main
    generate_file_pairs(
  File "/usr/local/lib/python3.9/site-packages/semgrep/test.py", line 318, in generate_file_pairs
    tested = {
  File "/usr/local/lib/python3.9/site-packages/semgrep/test.py", line 319, in <dictcomp>
    filename: score_output_json(
  File "/usr/local/lib/python3.9/site-packages/semgrep/test.py", line 203, in score_output_json
    raise Exception(
Exception: found results on ok'ed lines - lines={27} path=/src/wrongerrcheck/wrong-err-check.go
```

**Comment by aryx** [comment]
I can't reproduce locally on my machine.

**Comment by aryx** [comment]
I can reproduce with the installed version of semgrep (via pip3 install semgrep), but
when I try my local version of semgrep, even when I checkout release-0.41.0, I can't reproduce. Weird.

**Comment by aryx** [comment]
Ok, find a way to reproduce ... I had the wrong semgrep-core in my PATH.

**Comment by aryx** [comment]
ok, bisected to 9d4540db2eff77f3e353b6bf4fdc478b9ad96097 https://github.com/returntocorp/semgrep/pull/2618

**Comment by mschwager** [comment]
Hey @robinjmurphy,

This tricky bug was fixed in https://github.com/returntocorp/semgrep/pull/2659. This fix will go out with the Semgrep release early next week :+1:

**Comment by robinjmurphy** [comment]
Amazing. Thanks for a quick response! 🙌🏻
