### ISSUE TITLE
[Internal] can't run --json-time on semgrep-app code, index out of range error

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2740]
```
[pad@yrax dogfood (develop)]$ time semgrep --no-git-ignore --config semgrep_r_all.yml --json --json-time input/ > /tmp/res.json
running 1365 rules...
 47%|███████████████████████████████████████████████████████████████████████▏                                                                                 |635/1365
Traceback (most recent call last):
  File "/home/pad/.local/share/virtualenvs/semgrep-Bv0fltBr/bin/semgrep", line 33, in <module>
    sys.exit(load_entry_point('semgrep', 'console_scripts', 'semgrep')())
  File "/home/pad/github/semgrep/semgrep/semgrep/__main__.py", line 17, in main
    cli()
  File "/home/pad/github/semgrep/semgrep/semgrep/cli.py", line 457, in cli
    semgrep.semgrep_main.main(
  File "/home/pad/github/semgrep/semgrep/semgrep/semgrep_main.py", line 264, in main
    ) = CoreRunner(
  File "/home/pad/github/semgrep/semgrep/semgrep/core_runner.py", line 604, in invoke_semgrep
    ) = self._run_rules(rules, target_manager, profiler)
  File "/home/pad/github/semgrep/semgrep/semgrep/core_runner.py", line 550, in _run_rules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(
  File "/home/pad/github/semgrep/semgrep/semgrep/core_runner.py", line 432, in _run_rule
    output_json = profiler.track(
  File "/home/pad/github/semgrep/semgrep/semgrep/profile_manager.py", line 17, in track
    result = callable(*args, **kwargs)
  File "/home/pad/github/semgrep/semgrep/semgrep/spacegrep.py", line 111, in run_spacegrep
    ) + _extract_matching_time(output_json)
  File "/home/pad/github/semgrep/semgrep/semgrep/spacegrep.py", line 33, in _extract_matching_time
    res = json["time"]["targets"][0]["match_time"]
IndexError: list index out of range

real	13m26.279s
user	34m42.857s
sys	2m33.989s

```

**Comment by aryx** [comment]
I'll make a related PR where you can access semgrep_r_all.yml and the actual repo I ran this command on (semgrep-app and semgrep).

**Comment by aryx** [comment]
Also would be good if on the python side we were agglomerating all the time for the files, so that we could have numbers for each rule (or we can wait for semgrep-core to replace semgrep-python).

**Comment by IagoAbal** [comment]
This worked for me:
```
semgrep --no-git-ignore --config p/ci --json --json-time semgrep-app
```
Maybe the issue has already been fixed?
