### ISSUE TITLE
I'm getting an error regarding non json output, but I don't see any output.

### ISSUE THREAD

**Issue by squaresurf** [semgrep/semgrep#3043]
**Describe the bug**
I keep running into an error when trying to profile some rules with https://gitlab.com/dsearles/semgrep-profiler. I would love some tips on how to debug the error?

<details>
<summary>Error I'm running into:</summary>
<pre><code>
semgrep-core exit code: -11
unexpected non-json output while invoking semgrep-core:
--- semgrep-core stdout ---
--- end semgrep-core stdout ---
--- semgrep-core stderr ---
--- end semgrep-core stderr ---
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
Traceback (most recent call last):
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/core_runner.py", line 283, in _parse
_core_output
    return cast(Dict[str, Any], json.loads(semgrep_output))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
                                                                                                                                                        [7/1804]
Traceback (most recent call last):
  File "./profile_semgrep.py", line 120, in <module>
    main()
  File "./profile_semgrep.py", line 50, in main
    result = [
  File "./profile_semgrep.py", line 51, in <listcomp>
    time_rule(rule_key, rule, args.target) for (rule_key, rule) in rules.items()
  File "./profile_semgrep.py", line 110, in time_rule
    "time": timeit.repeat(
  File "/usr/lib/python3.8/timeit.py", line 238, in repeat
    return Timer(stmt, setup, timer, globals).repeat(repeat, number)
  File "/usr/lib/python3.8/timeit.py", line 205, in repeat
    t = self.timeit(number)
  File "/usr/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "./profile_semgrep.py", line 22, in run_semgrep
    return sgrep_cli()
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/cli.py", line 462, in cli
    semgrep.semgrep_main.main(
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 259, in main
    ) = CoreRunner(
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/core_runner.py", line 668, in invoke
_semgrep
    ) = runner_fxn(rules, target_manager, profiler)
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/core_runner.py", line 508, in _run_r
ules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/core_runner.py", line 400, in _run_r
ule
    output_json = profiler.track(
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/profile_manager.py", line 17, in tra
ck
    result = callable(*args, **kwargs)
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/core_runner.py", line 264, in _run_c
ore_command
    output_json = self._parse_core_output(out_bytes, err_bytes, returncode)
  File "/home/danielsearles/.cache/pypoetry/virtualenvs/semgrep-profiler-yCVFZyeZ-py3.8/lib/python3.8/site-packages/semgrep/core_runner.py", line 286, in _parse
_core_output
    raise SemgrepError(
semgrep.error.SemgrepError: semgrep-core exit code: -11
unexpected non-json output while invoking semgrep-core:
--- semgrep-core stdout ---
--- end semgrep-core stdout ---
--- semgrep-core stderr ---
--- end semgrep-core stderr ---
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
</code></pre>
</details>

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by aryx** [comment]
could be a segmentation fault ... sigsev is 11 I think.

**Comment by corrydiehl** [comment]
I believe I'm running into the same error while running as a container in Kubernetes. Here's the log output from the container after it died with an OOMKilled status

```
running 245 rules...
{
    "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
    "version": "2.1.0",
    "runs": [
        {
            "tool": {
                "driver": {
                    "name": "semgrep",
                    "semanticVersion": "0.49.0",
                    "rules": []
                }
            },
            "results": [],
            "invocations": [
                {
                    "executionSuccessful": true,
                    "toolExecutionNotifications": [
                        {
                            "descriptor": {
                                "id": "SemgrepError"
                            },
                            "message": {
                                "text": "semgrep-core exit code: -11\nunexpected non-json output while invoking semgrep-core:\n--- semgrep-core stdout ---\n\n--- end semgrep-core stdout ---\n--- semgrep-core stderr ---\n\n--- end semgrep-core stderr ---\nAn error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep"
                            },
                            "level": "error"
                        }
                    ]
                }
            ]
        }
    ]
```

**Comment by squaresurf** [comment]
I'm sorry for abandoning this. Now that I think back to what I was doing I think there is a good chance that I was running into something similar to a OOM issue like @corrydiehl. That being said, I haven't been running my profiler anymore and have moved onto other pressing things. #3044 will likely be very helpful for others that encounter issues like this.
