### ISSUE TITLE
Crash on empty file with blanket 'pattern-regex'

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3705]
Using the following `pattern-regex` rule:

```yaml
rules:
- id: any-file
  message: Match any file
  languages:
    - generic
  severity: INFO
  pattern-regex: ^.*
```

With a completely empty file:

```
$ echo -n "" | docker run --rm -v /tmp/test.yaml:/tmp/test.yaml -i returntocorp/semgrep:0.61.0 --config /tmp/test.yaml -
running 1 rules...
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/semgrep/cli.py", line 511, in cli
    semgrep.semgrep_main.main(
  File "/usr/local/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 289, in main
    ignored, returned_errors = rule_match_nosem(rule_match, strict)
  File "/usr/local/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 71, in rule_match_nosem
    if not rule_match.lines:
  File "/usr/local/lib/python3.9/site-packages/semgrep/rule_match.py", line 135, in lines
    result = list(itertools.islice(fd, start_line, end_line))
ValueError: Indices for islice() must be None or an integer: 0 <= x <= sys.maxsize.
```

With a 1-byte file:

```
$ echo -n "a" | docker run --rm -v /tmp/test.yaml:/tmp/test.yaml -i returntocorp/semgrep:0.61.0 --config /tmp/test.yaml -
running 1 rules...
/tmp/tmp89rr7_r3
severity:info rule:tmp.any-file: Match any file
1:a
ran 1 rules on 1 files: 1 findings
```

It looks like `rule_match` is expecting 1-indexed line numbers, but we may be receiving 0-indexed:

```python
# Start and end line are one-indexed, but the subsequent slice call is
# inclusive for start and exclusive for end, so only subtract from start
start_line = self.start["line"] - 1
end_line = self.end["line"]
```

**Comment by mschwager** [comment]
Looks like this worked in `0.50.0`, so maybe our indexing changed somewhere along the line:

```
$ echo -n "" | docker run --rm -v /tmp/test.yaml:/tmp/test.yaml -i returntocorp/semgrep:0.50.0 --config /tmp/test.yaml -
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
running 1 rules...
/tmp/tmpgjzjosvg
severity:info rule:tmp.any-file: Match any file
ran 1 rules on 1 files: 1 findings
```

**Comment by mschwager** [comment]
Huh, it works as expected with `pattern: ...` instead of `pattern-regex: ^.*`. I suspect this is a `pattern-regex` thing. This might've changed when we moved to `semgrep-core` whole rule file handling, which is when `semgrep-core` started handling `pattern-regex` :thinking:

**Comment by IagoAbal** [comment]
This is the function we use to compute line and column number for `pattern-regex` https://github.com/returntocorp/pfff/blob/0f98e5785f8cc3192d073673c42ff076a066350e/h_program-lang/Parse_info.ml#L532, it seems that given an empty file and charpos 0 it returns line 0 and column 0. Perhaps we just need to detect this special case `(0, 0)` and handle it specially, either in semgrep-core or in semgrep-cli.
