### ISSUE TITLE
Git merge-base fails

### ISSUE THREAD

**Issue by bt-nia** [semgrep/semgrep#3730]
**Describe the bug**
The bug appears in a merge request in our GitlabCI pipeline:
```
Using docker image sha256:4e62e9177f1c8fe9f83ad5877f0ba7e9878cb811bf9a27964b5b929271a62278 for returntocorp/semgrep-agent:v1 with digest returntocorp/semgrep-agent@sha256:7691b09267c29c900cb9eb75f28bf32c0b40609346f86c567ca24e73fcba12d0 ...
$ export DEVELOPER_DIR="$XCODE12_2"
$ GRADLE_COMMAND='./gradlew -s -Dorg.gradle.jvmargs= -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=false'
$ python -m semgrep_agent --config "p/secrets" --config "p/ci" --config "p/findsecbugs" --config "p/nginx" --config "p/r2c-best-practices"
| versions          - semgrep 0.61.0 on Python 3.9.6
| environment       - running in environment gitlab-ci, triggering event is 'pull_request'
| manage            - not logged in
=== setting up agent configuration
| using semgrep rules from https://semgrep.dev/c/p/secrets
| using semgrep rules from https://semgrep.dev/c/p/ci
| using semgrep rules from https://semgrep.dev/c/p/findsecbugs
| using semgrep rules from https://semgrep.dev/c/p/nginx
| using semgrep rules from https://semgrep.dev/c/p/r2c-best-practices
An unexpected error occurred
ERROR:root:
  RAN: /usr/bin/git merge-base --all e1ce7f89d456641e7195364699115d8be8b50347 FETCH_HEAD
  STDOUT:
  STDERR:
Traceback (most recent call last):
  File "/app/src/semgrep_agent/main.py", line 176, in main
    protected_main(**locals())
  File "/app/src/semgrep_agent/main.py", line 350, in protected_main
    meta.base_commit_ref,
  File "/usr/local/lib/python3.9/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/app/src/semgrep_agent/meta.py", line 323, in base_commit_ref
    git("merge-base", "--all", head_sha, "FETCH_HEAD").stdout.decode().strip()
  File "/usr/local/lib/python3.9/site-packages/sh.py", line 1566, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python3.9/site-packages/sh.py", line 822, in __init__
    self.wait()
  File "/usr/local/lib/python3.9/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.9/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 
  RAN: /usr/bin/git merge-base --all e1ce7f89d456641e7195364699115d8be8b50347 FETCH_HEAD
  STDOUT:
  STDERR:
```

**To Reproduce**
Sorry, could not reproduce locally

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
official docker image in CICD

**Comment by brendongo** [comment]
@bt-nia does this happen in all CI runs of semgrep-agent in gitlab CI or just this one run?

**Comment by bt-nia** [comment]
@brendongo thanks for looking at ths. 
Just one actually. I was able to find the issue here: We have `GIT_DEPTH=1` set, meaning our clones are shallow. This seems to not work well with Semgrep. After increasing the depth (in this case 30, for good measure) the error disappears.

**Comment by brendongo** [comment]
Yeah return code 1 here I think means git doesnt think that that commit is an ancestor of HEAD https://git-scm.com/docs/git-merge-base Seems like not being able to pull in history would cause that. Thanks for posting how you solved it @bt-nia !
