### ISSUE TITLE
ValueError: invalid width 0 (must be > 0) Exception

### ISSUE THREAD

**Issue by briankassouf** [semgrep/semgrep#4063]
**Describe the bug**
Latest version (0.69.0) results in a raised exception:

```
$ semgrep --version
0.69.0

$ semgrep --error --include '*.go' --exclude 'vendor' -f tools/semgrep/ci .
including files:
- *.go
excluding files:
- vendor
Running 8 rules...
100% 8/8 [00:09<00:00,  1.13s/it]
ran 8 rules on 1537 files: 0 findings
Traceback (most recent call last):
  File "/usr/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/semgrep/cli.py", line 662, in cli
    semgrep.semgrep_main.main(
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3.8/site-packages/semgrep/output.py", line 150, in managed_output
    output_handler.close()
  File "/usr/lib/python3.8/site-packages/semgrep/output.py", line 351, in close
    self.final_raise(final_error, error_stats)
  File "/usr/lib/python3.8/site-packages/semgrep/output.py", line 302, in final_raise
    terminal_wrap(
  File "/usr/lib/python3.8/site-packages/semgrep/util.py", line 123, in terminal_wrap
    wrapped_paras = ["\n".join(textwrap.wrap(p, width)) for p in paras]
  File "/usr/lib/python3.8/site-packages/semgrep/util.py", line 123, in <listcomp>
    wrapped_paras = ["\n".join(textwrap.wrap(p, width)) for p in paras]
  File "/usr/lib/python3.8/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/usr/lib/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)

Exited with code exit status 1
```

**Expected behavior**
This error was not present on earlier versions 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
alpine:3.13 container on CircleCI

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-483/valueerror-invalid-width-0-must-be-0-exception.

**Comment by aryx** [comment]
Can you narrow it down to a single file so we can try to reproduce locally. Can you share the offending file?
Can you run semgrep with --debug and copy-paste the trace?

**Comment by briankassouf** [comment]
After digging some more I realized prior to upgrading the output had this message:

```
ran 8 rules on 1534 files: 0 findings
found problems analyzing 2 files; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed cleanly
```

We apparently had a syntax error in a Go file that was not being compiled (due to build flags). Semgrep 0.69.0 appears to panic while trying to report `found problems analyzing 2 files; ...`

For context the syntax error looked like (note the extra parenthesis at the end): 

```
// +build tools
package tools
import (
	_ "golang.org/x/tools/cmd/goimports"
)
)
```

**Comment by brendongo** [comment]
@briankassouf I made a PR fixing the Invalid width exception.

re the syntax error: it sounds like it was actually invalid go code and seems unrelated to the bug above? This bug should be fixed in the next release next week let us know if it isn't!

**Comment by briankassouf** [comment]
@brendongo Thanks for the fix! And yes, the go syntax error was on our end and has since been fixed.
