### ISSUE TITLE
Bad settings format; please check or remove ...settings.yaml

### ISSUE THREAD

**Issue by stephencsnow** [semgrep/semgrep#4151]
**Describe the bug**
Seeing this error in our github pre-commit action:

```python
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/semgrep/cli.py", line 549, in cli
    possibly_notify_user()
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/semgrep/notifications.py", line 10, in possibly_notify_user
    from semgrep.settings import SETTINGS
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/semgrep/settings.py", line 63, in <module>
    SETTINGS = Settings()
  File "/home/runner/.cache/pre-commit/repodp61qq_a/py_env-python3.7/lib/python3.7/site-packages/semgrep/settings.py", line 41, in __init__
    f"Bad settings format; please check or remove {self._path}"
TypeError: Bad settings format; please check or remove /home/runner/.semgrep/settings.yml
```

**To Reproduce**
We currently use [this github action](https://github.com/pre-commit/action). Only started seeing this error after 0.70.0 upgrade.

**Expected behavior**
Should not fail CI.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
See above, using in pre-commit github action.

**Comment by stephencsnow** [comment]
Thank you @nbrahms!
