### ISSUE TITLE
UnboundLocalError: local variable 'target_manager' referenced before assignment

### ISSUE THREAD

**Issue by damiencarol** [semgrep/semgrep#4456]
**Describe the bug**
I have an error when I do a simple scan.

**To Reproduce**
I can only reproduce it on:
* Python 3.9
* semgrep 0.77.0, 0.76.0 (seems not here in 0.75.0)

```shell
python -m pip install semgrep==0.76.0
mkdir -p tests/scans/semgrep/
python -m semgrep --json --config=p/security-audit -o tests/scans/semgrep/latest.json "tests/payload/*"
```

**Expected behavior**
A report generated.

**Logs**

```
(.venv) [damien@damien vulnerabilities]$ python3 -m semgrep --sarif --config=p/python -o tests/scans/sarif/semgrep_latest.sarif "tests/payload/*"
Fetching rules from https://semgrep.dev/registry ...
Running 33 rules...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/damien/vulnerabilities/.venv/lib/python3.9/site-packages/semgrep/__main__.py", line 34, in <module>
    sys.exit(main())
  File "/home/damien/vulnerabilities/.venv/lib/python3.9/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/home/damien/vulnerabilities/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/damien/vulnerabilities/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/damien/vulnerabilities/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/damien/vulnerabilities/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/damien/vulnerabilities/.venv/lib/python3.9/site-packages/semgrep/cli.py", line 683, in cli
    semgrep.semgrep_main.main(
  File "/home/damien/vulnerabilities/.venv/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 229, in main
    ).invoke_semgrep(target_manager, profiler, filtered_rules)
UnboundLocalError: local variable 'target_manager' referenced before assignment
```

**What is the priority of the bug to you?**

- P1: important to fix or quite annoying

**Environment**
Local build in a virtual environment

**Comment by Sjord** [comment]
I can reproduce this by scanning a file that doesn't exist.

E.g. `foo.js` does not exist:

```
$ semgrep -l javascript -e '0=0' foo.js
File not found: foo.js
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 33, in <module>
    sys.exit(load_entry_point('semgrep==0.77.0', 'console_scripts', 'semgrep')())
  File "/usr/local/Cellar/semgrep/0.77.0/libexec/lib/python3.10/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/local/Cellar/semgrep/0.77.0/libexec/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/semgrep/0.77.0/libexec/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/semgrep/0.77.0/libexec/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/semgrep/0.77.0/libexec/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/semgrep/0.77.0/libexec/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/semgrep/0.77.0/libexec/lib/python3.10/site-packages/semgrep/commands/scan.py", line 682, in scan
    semgrep.semgrep_main.main(
  File "/usr/local/Cellar/semgrep/0.77.0/libexec/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 229, in main
    ).invoke_semgrep(target_manager, profiler, filtered_rules)
UnboundLocalError: local variable 'target_manager' referenced before assignment
```

Perhaps related to #4334, and [the following code](https://github.com/returntocorp/semgrep/blob/4fdfd0259314c4705c75a04bf09724a68ec32f76/semgrep/semgrep/semgrep_main.py#L202-L213):

```
    try:
        target_manager = TargetManager(
            includes=include,
            excludes=exclude,
            max_target_bytes=max_target_bytes,
            targets=target,
            respect_git_ignore=respect_git_ignore,
            skip_unknown_extensions=skip_unknown_extensions,
            file_ignore=get_file_ignore(),
        )
    except FilesNotFoundError as e:
        output_handler.handle_semgrep_error(e)
```

If a FilesNotFoundError is raised, `target_manager` is not assigned. Execution seems to continue and use `target_manager` later on.

Ping @brendongo.

**Comment by nbrahms** [comment]
Tagging @mmcqd @brendongo ... would either of y'all be able to take this one?

**Comment by yosefAlsuhaibani** [comment]
Going through old issues and our backlog: seems like this file doesn't exits anymore; unfortunately I can't quite pinpoint when we deleted the code that causes this bug. I'm marking this issue as resolved.
