### ISSUE TITLE
Crash on non-existent file

### ISSUE THREAD

**Issue by vmarkovtsev** [semgrep/semgrep#4462]
**Describe the bug**
`semgrep --config=whatever nonexistentfile.py` prints

```
File not found: nonexistentfile.py
Not sending pseudonymous metrics since metrics are configured to AUTO and server usage is False
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/semgrep/commands/scan.py", line 682, in scan
    semgrep.semgrep_main.main(
  File "/usr/local/lib/python3.8/dist-packages/semgrep/semgrep_main.py", line 229, in main
    ).invoke_semgrep(target_manager, profiler, filtered_rules)
UnboundLocalError: local variable 'target_manager' referenced before assignment
```

**What is the priority of the bug to you?**

P2

**Environment**
semgrep v0.77.0

**Comment by vmarkovtsev** [comment]
> nd either it wasn't prioritized or its priority is high

I think the bot meant "and either it wasn't prioritized or its priority is **not** high"

**Comment by vmarkovtsev** [comment]
@ievans indeed, this is a cosmetic issue, but also should be a quick fix.

**Comment by ievans** [comment]
Yes, I added some labels that will make stale bot go away. Thanks for reporting!
