### ISSUE TITLE
GitHub Action broken

### ISSUE THREAD

**Issue by HariSekhon** [semgrep/semgrep#4552]
**Describe the bug**
This used to work and suddenly broke. I re-ran the failed Github Actions workflow which succeeded but caused lots of false positives to appear in the Security tab, including for things that I don't even have in this repo like django.

2 issues:

1. Why did it fail the first time?
2. I believe semgrep is getting false positive alerts from semgrep's own agent files!

**Screenshots**

```
Run returntocorp/semgrep-action@v1
  with:
    config: p/security-audit p/secrets
    auditOn: push
    generateSarif: 1
/usr/bin/docker run --name returntocorpsemgrepagentv1_8cc960 --label 84217e --workdir /github/workspace --rm -e INPUT_CONFIG -e INPUT_AUDITON -e INPUT_GENERATESARIF -e INPUT_PUBLISHTOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/GitHub-Actions/GitHub-Actions":"/github/workspace" returntocorp/semgrep-agent:v1
| versions          - semgrep 0.79.0 on Python 3.9.7
| environment       - running in environment github-actions, triggering event is 'push'
| manage            - not logged in
=== setting up agent configuration
| using semgrep rules from https://semgrep.dev/c/p/security-audit
| using semgrep rules from https://semgrep.dev/c/p/secrets
=== looking for current issues in 1 file

=== failed command's STDOUT:



=== failed command's STDERR:



Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --time --timeout-threshold 3 --config https://semgrep.dev/c/p/security-audit --config https://semgrep.dev/c/p/secrets --enable-metrics --debug -o /tmp/tmpceivh7zb .` failed with exit code 2

This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose
and include any log output from above.
```
```
Run github/codeql-action/upload-sarif@v1
  with:
    sarif_file: semgrep.sarif
    checkout_path: /home/runner/work/GitHub-Actions/GitHub-Actions
    token: ***
    matrix: null
    wait-for-processing: false
Error: Path does not exist: semgrep.sarif
Error: Path does not exist: semgrep.sarif
    at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:148:15)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:136:30)
    at run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:50:47)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:67:9)
```

Re-running caused the issue in #4554.

I've had this error a few times now both for the semgrep CI sarif upload workflow to GitHub security tab, and also for the Semgrep cloud installed `semgrep.yml`.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

GitHub Actions:

My reusable workflow that I use across repos:
https://github.com/HariSekhon/GitHub-Actions/blob/master/.github/workflows/semgrep.yaml

Semgrep cloud installed workflow has same issue:
https://github.com/HariSekhon/GitHub-Actions/blob/master/.github/workflows/semgrep.yml

**Comment by ievans** [comment]
thanks @HariSekhon , we're looking into this. Feel free to join us on https://r2c.dev/slack as we fix

**Comment by mmcqd** [comment]
We rolled back to the previous semgrep-action release while we fix this. Let us know if anything is still broken.
