### ISSUE TITLE
compiled sgrep_lint does not work under Linux

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#456]
Not sure why but I had to rm -rf /usr/loca/bin/sgrep-lint-files/ to have 'make install'
create the appropriate symlinks.

But then I get an error when running sgrep-lint:

pad@yrax:~$ sgrep-lint 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
...
File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by DrewDennison** [comment]
@aryx I'm guessing the build infra clean up that @brendongo did fixed this accidentally but please re-open if you can't locally develop with `python3 -m semgrep`
