### ISSUE TITLE
Wrong encoding for --output url POST

### ISSUE THREAD

**Issue by Gby56** [semgrep/semgrep#4889]
When scanning and POSTing the data to a simpleHTTPServer in python, semgrep cli fails to do so because it falls back to latin-1 instead of utf-8.
I managed to fix it myself by just adding `.encode('utf-8')` in this exact line, simple as that !

```
posting to http://localhost:8000...
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 33, in <module>
    sys.exit(load_entry_point('semgrep==0.85.0', 'console_scripts', 'semgrep')())
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/semgrep/commands/scan.py", line 848, in scan
    output_handler.output(
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/semgrep/output.py", line 294, in output
    self._save_output(self.settings.output_destination, output)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/semgrep/output.py", line 357, in _save_output
    self._post_output(destination, output)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/semgrep/output.py", line 370, in _post_output
    r = requests.post(output_url, data=output, timeout=10)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/semgrep/0.85.0/libexec/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1327, in _send_request
    body = _encode(body, 'body')
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 166, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2506' in position 715: Body ('┆') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

https://github.com/returntocorp/semgrep/blob/70e92da0626d8f893b846006b64418d84c9ee9fe/semgrep/semgrep/output.py#L372

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1039/wrong-encoding-for-output-url-post.

**Comment by markvdesign** [comment]
I have this very same issue where outputting to a URL fails with the same encoding error message. Any chance we can reopen this issue?

**Comment by robbjass** [comment]
This might help:
`r = requests.post(output_url, data=output.encode('utf-8'), timeout=10)`
