### ISSUE TITLE
TypeError when run 0.86.3

### ISSUE THREAD

**Issue by vmarkovtsev** [semgrep/semgrep#4910]
I caught a blocking error in 0.86.3
CI: https://github.com/athenianco/athenian-api/runs/5718170879?check_suite_focus=true
```
Run semgrep --config p/r2c-security-audit --severity ERROR --disable-version-check --error
Traceback (most recent call last):
  File "/home/runner/.local/bin/semgrep", line 5, in <module>
    from semgrep.__main__ import main
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/__main__.py", line 5, in <module>
    from semgrep.cli import cli
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/cli.py", line 4, in <module>
    from semgrep.commands.ci import ci
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/commands/ci.py", line 34, in <module>
    from semgrep.semgrep_app import ScanHandler
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/semgrep_app.py", line 2[9](https://github.com/athenianco/athenian-api/runs/5718170879?check_suite_focus=true#step:8:9), in <module>
    max_retries=Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1048/typeerror-when-run-0863.

**Comment by emjin** [comment]
The current latest is 0.86.5 (0.86 was a big shift in terms of how we run semgrep in CI, so despite our best efforts we had to release some patches). Would you mind checking if this error persists in 0.86.5?

**Comment by brendongo** [comment]
We fixed this in 0.86.5 https://github.com/returntocorp/semgrep/commit/ea7c954e954bd1b8034b36ab91b31a2071fcbeb7#diff-65d26b773523b71e73b4aa4af255e1430a6ce86744ce9c84e72e3c53ce5e583eR132

**Comment by ievans** [comment]
Thanks for the report @vmarkovtsev !

**Comment by vmarkovtsev** [comment]
Thanks for a quick fix as usual! I'll upgrade to the latest version when dependabot PRs next week 👍
