### ISSUE TITLE
Error running r2c-internal-project-depends-on on version 0.86.5 Semgrep

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#4982]
**Describe the bug**
When attempting to run r2c-internal-project-depends-on on version 0.86.5 it throws the following error:

```
semgrep --version
0.86.5

Scanning 209 files.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|209/209 tasks
Traceback (most recent call last):
  File "/opt/homebrew/bin/semgrep", line 33, in <module>
    sys.exit(load_entry_point('semgrep==0.86.5', 'console_scripts', 'semgrep')())
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/semgrep/commands/scan.py", line 868, in scan
    ) = semgrep.semgrep_main.main(
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 340, in main
    rule_matches_by_rule, semgrep_errors, all_targets, profiling_data = run_rules(
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 168, in run_rules
    ) = dep_aware_rule.run_dependency_aware_rule(
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/semgrep/dependency_aware_rule.py", line 111, in run_dependency_aware_rule
    depends_on_entries, find_and_parse_lockfiles(lockfile_target)
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/dependencyparser/package_restrictions.py", line 23, in find_and_parse_lockfiles
    for lockfile in find_lockfiles(current_dir):
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/dependencyparser/find_lockfiles.py", line 29, in find_lockfiles
    yield from find_lockfiles(full_path, frozenset(new_paths))
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/dependencyparser/find_lockfiles.py", line 29, in find_lockfiles
    yield from find_lockfiles(full_path, frozenset(new_paths))
  File "/opt/homebrew/Cellar/semgrep/0.86.5/libexec/lib/python3.10/site-packages/dependencyparser/find_lockfiles.py", line 23, in find_lockfiles
    if entry.is_dir() and (
PermissionError: [Errno 13] Permission denied: '/usr/sbin/weakpass_edit'

```

**To Reproduce**
Run the following rule https://github.com/returntocorp/semgrep-rules/blob/1ab17a13a15979c24aad362861fd3878a5424192/javascript/express/security/audit/check-outdated-sanitize-html.yaml 

```
semgrep --config ./check-outdated-sanitize-html.yaml ./test.js
```

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "sanitize-html": "1.4.2"
  }
}

```
test.js
```
const sanitizeHtml = require('sanitize-html')

sanitizeHtml(html)
```

**Expected behavior**
It should check the package.json for the version 1.4.2 and check the javascript for the use of sanitize html

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Environment**
macos monterey m1 12.2.1 
semgrep 0.86.5

**Use case**
It will enable the creation of additional rules using the r2c-internal-project-depends-on property.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1127/error-running-r2c-internal-project-depends-on-on-version-0865-semgrep.

**Comment by mmcqd** [comment]
@LewisArdern can you try this on the latest version of semgrep? The code where that error is occurring has been rewritten and I don't believe it should happen anymore. The syntax of the key has changed a bit, and you should know that `package.json` files don't get scanned, only `package-lock.json`. Check out the docs for more info: https://semgrep.dev/docs/experiments/r2c-internal-project-depends-on/

**Comment by aryx** [comment]
Is this fixed @LewisArdern?
Reopen if not.
