### ISSUE TITLE
semgrep-lint crashes if /tmp doesn't exist

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#525]
**Describe the bug**

I think this line is where we expect `/tmp` to exist https://github.com/returntocorp/semgrep/commit/bc39236b35c99eea436228189eff5f4097266abd#diff-2c8973c1a63d95e440b7c99e07c47b7dR189 and semgrep-lint crashes if it doesn't.

**To Reproduce**

1. Make sure there's no `/tmp`
2. Run `sgrep` tool via bento

**Expected behavior**

semgrep should use `/var/tmp` in docker contexts where that path is used instead of `/tmp`

**Screenshots**

```
[INFO] 5460.999965667725 root:docker - Running sgrep using installed binary
[INFO] 5701.299667358398 root:docker - sgrep: Returned code 2 with stdout[:4000]:
stderr[:4000]
Fatal error: exception (Failure
  "sgrep_lint: wrong format. could not parse the pattern $X == $X (exn = (Sys_error \"/tmp/tmp-431-508804.py: No such file or directory\"))")
non-zero return code while invoking sgrep with:
	sgrep -lang python -rules_file /var/tmp/tmp15_abs8h /src/bento.py
Command '['sgrep', '-lang', 'python', '-rules_file', '/var/tmp/tmp15_abs8h', '/src/bento.py']' returned non-zero exit status 2.
An error occurred while invoking the sgrep engine; please help us fix this by filing an an issue at https://sgrep.dev
[ERROR] 5863.148212432861 root:tool_runner - Traceback (most recent call last):
  File "/app/bento/tool_runner.py", line 257, in _setup_and_run_single_tool
    results = self._run_single_tool(bar, ix, tool, baseline)
  File "/app/bento/tool_runner.py", line 226, in _run_single_tool
    tool.tool_id(), tool.results(self.paths, self.use_cache), baseline
  File "/app/bento/tool/tool.py", line 269, in results
    violations = self._get_findings_from_run(paths)
  File "/app/bento/tool/tool.py", line 234, in _get_findings_from_run
    raw = self.run(path_list)
  File "/app/bento/extra/base_sgrep.py", line 122, in run
    output_str = self.run_command(files).stdout.split("\n")
  File "/app/bento/tool/runner/docker.py", line 247, in run_command
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['--config', '.bento/sgrep.yml', '--json', '--skip-pattern-validation']' returned non-zero exit status 2.
```

**Environment**

returntocorp/bento docker image

**Comment by ievans** [comment]
Probably the preferred solution here is to use NamedTemporaryFile as is done elsewhere in the Python
