### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/src'

### ISSUE THREAD

**Issue by zhuxindong** [semgrep/semgrep#5488]
when i run  "docker run -v "${PWD}:/src" returntocorp/semgrep semgrep --config=auto”

then error occuered:
```shell
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/semgrep/cli.py", line 588, in cli
    semgrep.config_resolver.adjust_for_docker()
  File "/usr/local/lib/python3.9/site-packages/semgrep/config_resolver.py", line 443, in adjust_for_docker
    os.chdir(SRC_DIRECTORY)
PermissionError: [Errno 13] Permission denied: '/src'
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1489/permissionerror-[errno-13]-permission-denied-src. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ievans** [comment]
Maybe related to https://github.com/returntocorp/semgrep/issues/5479?
