### ISSUE TITLE
Failure to execute in GHA for a private project

### ISSUE THREAD

**Issue by vmarkovtsev** [semgrep/semgrep#5556]
I execute semgrep in GitHub Actions in my private project. The trigger event is `pull_request`. I see the following log:
```
/usr/bin/docker run --name returntocorpsemgrepagentv1_157c18 --label 72882e --workdir /github/workspace --rm -e PIP_CACHE -e INPUT_CONFIG -e INPUT_PUBLISHTOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/precomputer/precomputer":"/github/workspace" returntocorp/semgrep-agent:v1
=== Running: SEMGREP_RULES="p/r2c-security-audit" semgrep ci
Running `semgrep ci` without API token but with configs ('p/r2c-security-audit',)
Scan environment:
  versions    - semgrep 0.98.0 on python 3.[10](https://github.com/athenianco/precomputer/runs/6916138454?check_suite_focus=true#step:4:11).5
  environment - running in environment github-actions, triggering event is pull_request
Command '['git', 'fetch', 'origin', '--depth=1', '--force', '--update-head-ok', 'mem-accounts-new:mem-accounts-new']' returned non-zero exit status [12](https://github.com/athenianco/precomputer/runs/6916138454?check_suite_focus=true#step:4:13)8.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 306, in ci
    with fix_head_if_github_action(metadata):
  File "/usr/local/lib/python3.10/contextlib.py", line [13](https://github.com/athenianco/precomputer/runs/6916138454?check_suite_focus=true#step:4:14)5, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 83, in fix_head_if_github_action
    assert metadata.head_branch_hash is not None  # Not none when github action PR
  File "/usr/local/lib/python3.10/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 250, in head_branch_hash
    commit = self._get_latest_commit_hash_in_branch(head_branch_name)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 238, in _get_latest_commit_hash_in_branch
    self._shallow_fetch_branch(branch_name)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 2[15](https://github.com/athenianco/precomputer/runs/6916138454?check_suite_focus=true#step:4:16), in _shallow_fetch_branch
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 5[24](https://github.com/athenianco/precomputer/runs/6916138454?check_suite_focus=true#step:4:25), in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'fetch', 'origin', '--depth=1', '--force', '--update-head-ok', 'mem-accounts-new:mem-accounts-new']' returned non-zero exit status 1[28](https://github.com/athenianco/precomputer/runs/6916138454?check_suite_focus=true#step:4:29).
```

The GHA  config is
```
semgrep:
    name: Semgrep
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c-security-audit
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1515/failure-to-execute-in-gha-for-a-private-project. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by vmarkovtsev** [comment]
I changed the config as follows and everything worked:
```
semgrep:
    name: Semgrep
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c-security-audit
```
