### ISSUE TITLE
Pull requests scans failing as of semgrep version 0.98 on git fetch

### ISSUE THREAD

**Issue by pzhou-splunk** [semgrep/semgrep#5562]
**Describe the bug**
We run semgrep scans via GitHub actions on the `pull_request_target` event for our repos in https://github.com/splunk-soar-connectors. As of semgrep version 0.98, the scans have started crashing when running against forked pull requests with the following output:

```
Scan environment:
  versions    - semgrep 0.98.0 on python 3.10.5
  environment - running in environment github-actions, triggering event is pull_request_target
Command '['git', 'fetch', 'origin', '--depth=1', '--force', '--update-head-ok', 'various-updates:various-updates']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 306, in ci
    with fix_head_if_github_action(metadata):
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 83, in fix_head_if_github_action
    assert metadata.head_branch_hash is not None  # Not none when github action PR
  File "/usr/local/lib/python3.10/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 250, in head_branch_hash
    commit = self._get_latest_commit_hash_in_branch(head_branch_name)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 238, in _get_latest_commit_hash_in_branch
    self._shallow_fetch_branch(branch_name)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 215, in _shallow_fetch_branch
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'fetch', 'origin', '--depth=1', '--force', '--update-head-ok', 'various-updates:various-updates']' returned non-zero exit status 128.
```

**To Reproduce**
Run `semgrep-action@v1` on a `pull_request_target` event for a forked repo
Example workflow run - https://github.com/splunk-soar-connectors/censys/runs/6921635664?check_suite_focus=true

**Expected behavior**
Scans are able to run normally

**What is the priority of the bug to you?**
- [X] P1: important to fix or quite annoying

**Environment**
GitHub Actions

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1518/pull-requests-scans-against-forks-failing-as-of-semgrep-version-098. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by anshumanbh** [comment]
We are experiencing a bunch of failures all of a sudden. An example run failure:

```
Scan environment:
  versions    - semgrep 0.98.0 on python 3.10.5
  environment - running in environment github-actions, triggering event is pull_request
  semgrep.dev - authenticated as ThirtyMadison
Command '['git', 'fetch', 'origin', '--depth=1', '--force', '--update-head-ok', 'feature/sc-10101[7](https://github.com/ThirtyMadison/data/runs/6922825036?check_suite_focus=true#step:4:8)/update-claim-results-model:feature/sc-101017/update-claim-results-model']' returned non-zero exit status 12[8](https://github.com/ThirtyMadison/data/runs/6922825036?check_suite_focus=true#step:4:9).
Traceback (most recent call last):
  File "/usr/local/lib/python3.[10](https://github.com/ThirtyMadison/data/runs/6922825036?check_suite_focus=true#step:4:11)/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 306, in ci
    with fix_head_if_github_action(metadata):
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 83, in fix_head_if_github_action
    assert metadata.head_branch_hash is not None  # Not none when github action PR
  File "/usr/local/lib/python3.10/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 250, in head_branch_hash
    commit = self._get_latest_commit_hash_in_branch(head_branch_name)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 238, in _get_latest_commit_hash_in_branch
    self._shallow_fetch_branch(branch_name)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 215, in _shallow_fetch_branch
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'fetch', 'origin', '--depth=1', '--force', '--update-head-ok', 'feature/sc-101017/update-claim-results-model:feature/sc-101017/update-claim-results-model']' returned non-zero exit status 128.
Error: Process completed with exit code 2.
```

**Comment by spencerdrak** [comment]
Thanks for the reports! We are investigating this issue and will post updates here as we have them.

**Comment by spencerdrak** [comment]
Hey there @anshumanbh and @pzhou-splunk - One thing we've noticed is that the error doesn't occur with `actions/checkout@v3`, and we can only reproduce with `actions/checkout@v1`. Does this happen to be the same version of the checkout step that you folks are using? Upgrading this if possible may be a fix for the time being. 

We're going to continue looking for the root cause here, though.

**Comment by anshumanbh** [comment]
@spencerdrak We are using `actions/checkout@v3`. Our semgrep.yml looks like below:

```
name: Semgrep
on:
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 0 0 * * 0
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
```

**Comment by anshumanbh** [comment]
A different error we saw in Github Actions run:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 316, in ci
    scan_handler.start_scan(metadata_dict)
  File "/usr/local/lib/python3.10/site-packages/semgrep/app/scans.py", line 79, in start_scan
    response = state.app_session.post(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 6[35](https://github.com/ThirtyMadison/data/runs/6922613098?check_suite_focus=true#step:4:36), in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/app/session.py", line 1[38](https://github.com/ThirtyMadison/data/runs/6922613098?check_suite_focus=true#step:4:39), in request
    return super().request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='semgrep.dev', port=4[43](https://github.com/ThirtyMadison/data/runs/6922613098?check_suite_focus=true#step:4:44)): Max retries exceeded with url: /api/agent/deployments/5671/scans (Caused by ResponseError('too many 500 error responses'))
Could not start scan HTTPSConnectionPool(host='semgrep.dev', port=[44](https://github.com/ThirtyMadison/data/runs/6922613098?check_suite_focus=true#step:4:45)3): Max retries exceeded with url: /api/agent/deployments/5671/scans (Caused by ResponseError('too many 500 error responses'))
```

**Comment by spencerdrak** [comment]
@anshumanbh re: the different error you saw - we are also experiencing an outage on the app side which our team is looking into, and status should be posted in our community slack if you want to follow along there. It's a separate issue, and we're tracking, but thanks for the report!

In terms of the v1/v3 checkout step, we'll continue looking into this and try to reproduce on our end. If we need more info, we'll follow up here. Thanks!

**Comment by spencerdrak** [comment]
@anshumanbh we're not able to reproduce the error using the `actions/checkout@v3` - you mentioned that a bunch of failures were occurring, are they all using `actions/checkout@v3` or are some using an older version? Also, the `requests.exceptions.RetryError` you noted shouldn't be occurring anymore, so a run using checkout v3 is at least succeeding on our end (unless there's some other sort of configuration difference).

**Comment by anshumanbh** [comment]
@spencerdrak Yes, all our Github Action workflows are using `actions/checkout@v3`

**Comment by pzhou-splunk** [comment]
@spencerdrak thanks for following up

Unfortunately, the scans are still failing for us using `actions/checkout@v3`

**Comment by spencerdrak** [comment]
@pzhou-splunk sure, we're looking into this again now. If we have anymore questions, we'll drop them here.

**Comment by brendongo** [comment]
```
name: SemgrepTest

on:
  workflow_dispatch:
  pull_request:

jobs:
  v3:
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory '*'
      - run: git fetch --depth=1 origin BRANCH_NAME_HERE
      - run: git fetch --depth=1 origin BRANCH_NAME_HERE:BRANCH_NAME_HERE
```

@anshumanbh are you able to make a PR with the above replacing BRANCH_NAME_HERE. We should be able to see the error message you are getting.

**Comment by spencerdrak** [comment]
@pzhou-splunk is there any chance you'd also be able to add the above debugging steps to your semgrep action? We've been unsuccessful in reproducing the error, even when trying to use the same action as your runs.

**Comment by invidian** [comment]
For me, action fails as semgrep tries to fetch a feature branch which exists in my fork from the upstream repository, which of course does not have a reference there (all forks are the same git repository, but branches visibility is separate). That does seem like a bug.

**Comment by ankush** [comment]
@brendongo @spencerdrak 


Like @invidian also mentioned this affects forks primarily. The branch doesn't exist on the original repository so fetching it will result in an error. 


Example PR run: https://github.com/frappe/frappe/runs/6965225731?check_suite_focus=true 


If you want raw logs of workflow you suggested, here they are:

```
---- clipped a lot of irrelevant info, lmk if required ---
2022-06-20T10:39:22.5734478Z Resolving deltas: 100% (431/431)
2022-06-20T10:39:22.5736399Z Resolving deltas: 100% (431/431), done.
2022-06-20T10:39:22.6081472Z From https://github.com/frappe/frappe
2022-06-20T10:39:22.6082250Z  * [new ref]         e3fabe93b1b59827454d1e1dcd28fbc6e6a8fa54 -> pull/17228/merge
2022-06-20T10:39:22.6103215Z ##[endgroup]
2022-06-20T10:39:22.6103813Z ##[group]Determining the checkout info
2022-06-20T10:39:22.6107332Z ##[endgroup]
2022-06-20T10:39:22.6107835Z ##[group]Checking out the ref
2022-06-20T10:39:22.6113255Z [command]/usr/bin/git checkout --progress --force refs/remotes/pull/17228/merge
2022-06-20T10:39:23.0396643Z Note: switching to 'refs/remotes/pull/17228/merge'.
2022-06-20T10:39:23.0396930Z 
2022-06-20T10:39:23.0399624Z You are in 'detached HEAD' state. You can look around, make experimental
2022-06-20T10:39:23.0400268Z changes and commit them, and you can discard any commits you make in this
2022-06-20T10:39:23.0400679Z state without impacting any branches by switching back to a branch.
2022-06-20T10:39:23.0400998Z 
2022-06-20T10:39:23.0401245Z If you want to create a new branch to retain commits you create, you may
2022-06-20T10:39:23.0401626Z do so (now or later) by using -c with the switch command. Example:
2022-06-20T10:39:23.0401795Z 
2022-06-20T10:39:23.0401947Z   git switch -c <new-branch-name>
2022-06-20T10:39:23.0402086Z 
2022-06-20T10:39:23.0402179Z Or undo this operation with:
2022-06-20T10:39:23.0402310Z 
2022-06-20T10:39:23.0402387Z   git switch -
2022-06-20T10:39:23.0402484Z 
2022-06-20T10:39:23.0402741Z Turn off this advice by setting config variable advice.detachedHead to false
2022-06-20T10:39:23.0403178Z 
2022-06-20T10:39:23.0403469Z HEAD is now at e3fabe9 Merge bb7ee92198b40444464b93cea6b39a1e66e7cf90 into f40c82d4d8aeeb75ae042cd2c57acf7676ace2a7
2022-06-20T10:39:23.0426530Z ##[endgroup]
2022-06-20T10:39:23.0459004Z [command]/usr/bin/git log -1 --format='%H'
2022-06-20T10:39:23.0488238Z 'e3fabe93b1b59827454d1e1dcd28fbc6e6a8fa54'
2022-06-20T10:39:23.0816617Z ##[group]Run git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules
2022-06-20T10:39:23.0817119Z [36;1mgit clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules[0m
2022-06-20T10:39:23.0820527Z shell: sh -e {0}
2022-06-20T10:39:23.0820733Z ##[endgroup]
2022-06-20T10:39:23.1951600Z Cloning into 'frappe-semgrep-rules'...
2022-06-20T10:39:23.3973134Z ##[group]Run actions/checkout@v3
2022-06-20T10:39:23.3973332Z with:
2022-06-20T10:39:23.3973519Z   repository: frappe/frappe
2022-06-20T10:39:23.3973887Z   token: ***
2022-06-20T10:39:23.3976986Z   ssh-strict: true
2022-06-20T10:39:23.3977210Z   persist-credentials: true
2022-06-20T10:39:23.3977412Z   clean: true
2022-06-20T10:39:23.3977595Z   fetch-depth: 1
2022-06-20T10:39:23.3977770Z   lfs: false
2022-06-20T10:39:23.3977950Z   submodules: false
2022-06-20T10:39:23.3978152Z   set-safe-directory: true
2022-06-20T10:39:23.3978347Z ##[endgroup]
2022-06-20T10:39:23.3981503Z ##[command]/usr/bin/docker exec  3a73edf5d5ed1ae37aa07cab6deffacc5aae6592d20f2e3543a85e1453ad4eaf sh -c "cat /etc/*release | grep ^ID"
2022-06-20T10:39:23.7278700Z Syncing repository: frappe/frappe
2022-06-20T10:39:23.7289634Z ##[group]Getting Git version info
2022-06-20T10:39:23.7290300Z Working directory is '/__w/frappe/frappe'
2022-06-20T10:39:23.7346895Z [command]/usr/bin/git version
2022-06-20T10:39:23.7394377Z git version 2.36.1
2022-06-20T10:39:23.7427902Z ##[endgroup]
2022-06-20T10:39:23.7447994Z Temporarily overriding HOME='/__w/_temp/378a51fa-5136-4042-80fd-aed5ace73ced' before making global git config changes
2022-06-20T10:39:23.7448665Z Adding repository directory to the temporary git global config as a safe directory
2022-06-20T10:39:23.7454236Z [command]/usr/bin/git config --global --add safe.directory /__w/frappe/frappe
2022-06-20T10:39:23.7498468Z [command]/usr/bin/git config --local --get remote.origin.url
2022-06-20T10:39:23.7520980Z https://github.com/frappe/frappe
2022-06-20T10:39:23.7531829Z ##[group]Removing previously created refs, to avoid conflicts
2022-06-20T10:39:23.7535830Z [command]/usr/bin/git rev-parse --symbolic-full-name --verify --quiet HEAD
2022-06-20T10:39:23.7559477Z HEAD
2022-06-20T10:39:23.7570395Z [command]/usr/bin/git rev-parse --symbolic-full-name --branches
2022-06-20T10:39:23.7600020Z ##[endgroup]
2022-06-20T10:39:23.7601627Z ##[group]Cleaning the repository
2022-06-20T10:39:23.7603013Z [command]/usr/bin/git clean -ffdx
2022-06-20T10:39:23.7738763Z Removing frappe-semgrep-rules/
2022-06-20T10:39:23.7746626Z [command]/usr/bin/git reset --hard HEAD
2022-06-20T10:39:23.8066111Z HEAD is now at e3fabe9 Merge bb7ee92198b40444464b93cea6b39a1e66e7cf90 into f40c82d4d8aeeb75ae042cd2c57acf7676ace2a7
2022-06-20T10:39:23.8076873Z ##[endgroup]
2022-06-20T10:39:23.8077903Z ##[group]Disabling automatic garbage collection
2022-06-20T10:39:23.8080579Z [command]/usr/bin/git config --local gc.auto 0
2022-06-20T10:39:23.8115241Z ##[endgroup]
2022-06-20T10:39:23.8115618Z ##[group]Setting up auth
2022-06-20T10:39:23.8123837Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-06-20T10:39:23.8181617Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-06-20T10:39:23.8430444Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-06-20T10:39:23.8459868Z http.https://github.com/.extraheader
2022-06-20T10:39:23.8470186Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-06-20T10:39:23.8502547Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-06-20T10:39:23.8703977Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2022-06-20T10:39:23.8750163Z ##[endgroup]
2022-06-20T10:39:23.8750552Z ##[group]Fetching the repository
2022-06-20T10:39:23.8762152Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +e3fabe93b1b59827454d1e1dcd28fbc6e6a8fa54:refs/remotes/pull/17228/merge
2022-06-20T10:39:24.0414376Z remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
2022-06-20T10:39:24.0542080Z ##[endgroup]
2022-06-20T10:39:24.0542516Z ##[group]Determining the checkout info
2022-06-20T10:39:24.0548239Z ##[endgroup]
2022-06-20T10:39:24.0550643Z ##[group]Checking out the ref
2022-06-20T10:39:24.0558235Z [command]/usr/bin/git checkout --progress --force refs/remotes/pull/17228/merge
2022-06-20T10:39:24.0913608Z HEAD is now at e3fabe9 Merge bb7ee92198b40444464b93cea6b39a1e66e7cf90 into f40c82d4d8aeeb75ae042cd2c57acf7676ace2a7
2022-06-20T10:39:24.0922332Z ##[endgroup]
2022-06-20T10:39:24.0971374Z [command]/usr/bin/git log -1 --format='%H'
2022-06-20T10:39:24.1001679Z 'e3fabe93b1b59827454d1e1dcd28fbc6e6a8fa54'
2022-06-20T10:39:24.1169172Z ##[group]Run git config --global --add safe.directory '*'
2022-06-20T10:39:24.1169487Z [36;1mgit config --global --add safe.directory '*'[0m
2022-06-20T10:39:24.1169799Z shell: sh -e {0}
2022-06-20T10:39:24.1169970Z ##[endgroup]
2022-06-20T10:39:24.2147600Z ##[group]Run git fetch --depth=1 origin sgrep
2022-06-20T10:39:24.2147885Z [36;1mgit fetch --depth=1 origin sgrep[0m
2022-06-20T10:39:24.2148186Z shell: sh -e {0}
2022-06-20T10:39:24.2148380Z ##[endgroup]
2022-06-20T10:39:24.4554383Z fatal: couldn't find remote ref sgrep
2022-06-20T10:39:24.4617141Z ##[error]Process completed with exit code 128.
2022-06-20T10:39:24.4686674Z Post job cleanup.
2022-06-20T10:39:24.4689401Z ##[command]/usr/bin/docker exec  3a73edf5d5ed1ae37aa07cab6deffacc5aae6592d20f2e3543a85e1453ad4eaf sh -c "cat /etc/*release | grep ^ID"
2022-06-20T10:39:24.8343159Z [command]/usr/bin/git version
2022-06-20T10:39:24.8393171Z git version 2.36.1
2022-06-20T10:39:24.8438320Z Copying '/github/home/.gitconfig' to '/__w/_temp/36058438-ebd1-440a-98d8-0d15e5c1c93e/.gitconfig'
2022-06-20T10:39:24.8452703Z Temporarily overriding HOME='/__w/_temp/36058438-ebd1-440a-98d8-0d15e5c1c93e' before making global git config changes
2022-06-20T10:39:24.8457161Z Adding repository directory to the temporary git global config as a safe directory
2022-06-20T10:39:24.8466016Z [command]/usr/bin/git config --global --add safe.directory /__w/frappe/frappe
2022-06-20T10:39:24.8510612Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-06-20T10:39:24.8545036Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-06-20T10:39:24.8739430Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-06-20T10:39:24.8770629Z http.https://github.com/.extraheader
2022-06-20T10:39:24.8783300Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-06-20T10:39:24.8815518Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-06-20T10:39:24.9203324Z Post job cleanup.
2022-06-20T10:39:24.9206156Z ##[command]/usr/bin/docker exec  3a73edf5d5ed1ae37aa07cab6deffacc5aae6592d20f2e3543a85e1453ad4eaf sh -c "cat /etc/*release | grep ^ID"
2022-06-20T10:39:25.2541281Z [command]/usr/bin/git version
2022-06-20T10:39:25.2594527Z git version 2.36.1
2022-06-20T10:39:25.2645443Z Copying '/github/home/.gitconfig' to '/__w/_temp/3941e668-e50e-4acc-be61-1f3e974d8f18/.gitconfig'
2022-06-20T10:39:25.2670247Z Temporarily overriding HOME='/__w/_temp/3941e668-e50e-4acc-be61-1f3e974d8f18' before making global git config changes
2022-06-20T10:39:25.2670678Z Adding repository directory to the temporary git global config as a safe directory
2022-06-20T10:39:25.2671270Z [command]/usr/bin/git config --global --add safe.directory /__w/frappe/frappe
2022-06-20T10:39:25.2710679Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-06-20T10:39:25.2743054Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-06-20T10:39:25.2942323Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-06-20T10:39:25.2973483Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-06-20T10:39:25.3435702Z Stop and remove container: f2004d01fb1e4710b47b65c7a925b6fb_returntocorpsemgrep_b6358d
2022-06-20T10:39:25.3440910Z ##[command]/usr/bin/docker rm --force 3a73edf5d5ed1ae37aa07cab6deffacc5aae6592d20f2e3543a85e1453ad4eaf
2022-06-20T10:39:25.6345135Z 3a73edf5d5ed1ae37aa07cab6deffacc5aae6592d20f2e3543a85e1453ad4eaf
2022-06-20T10:39:25.6363142Z Remove container network: github_network_de8b4d12b04d4e95a451e5f59ddf1c75
2022-06-20T10:39:25.6368013Z ##[command]/usr/bin/docker network rm github_network_de8b4d12b04d4e95a451e5f59ddf1c75
2022-06-20T10:39:25.7328662Z github_network_de8b4d12b04d4e95a451e5f59ddf1c75
2022-06-20T10:39:25.7454852Z Cleaning up orphan processes
```

**Comment by ankush** [comment]
@brendongo Following line added in https://github.com/returntocorp/semgrep/pull/5453 is causing this failure on forks. 

https://github.com/returntocorp/semgrep/blob/08703530b023082f4a6d110c10a8211fb8415311/semgrep/semgrep/commands/ci.py#L83 


If I understood this it's fetching last commit on `pull_request.head.ref` which is a branch name fromm which PR is created. But in case of **fork**, last commit is still found by shallow fetch on `origin`.

https://github.com/returntocorp/semgrep/blob/67ee0cdd8914a71d8a63805ea9320f02cb2c39d9/cli/src/semgrep/meta.py#L211-L229 



Just using `pull_request.head.sha` should give last commit, I am not fully sure if that's the solution though as I am not aware of how diff-aware scanning is implemented. . 

ref: https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request

**Comment by spencerdrak** [comment]
Thanks for the detailed report @ankush - we're looking at how we want to address this and will provide updates or ask for more info here.

**Comment by ankush** [comment]
@spencerdrak is it possible to release this fix as a patch release?

**Comment by anshumanbh** [comment]
@spencerdrak Hi Spencer, we are seeing another failure:

```
Scan environment:
  versions    - semgrep 0.101.0 on python 3.10.5
  environment - running in environment github-actions, triggering event is pull_request
  semgrep.dev - authenticated as redacted
Fixing git state for github action pull request
Not on head ref: redacted[7](https://github.com/redacted/redacted/runs/redacted?check_suite_focus=true#step:4:8)aee73ae; checking that out now.
Command '['git', 'checkout', 'e[8](https://github.com/redacted/redacted/runs/redacted?check_suite_focus=true#step:4:9)5632dbaa[9](https://github.com/redacted/redacted/runs/redacted?check_suite_focus=true#step:4:10)0a3b5e150a4a9b39bd2367aee73ae']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/usr/local/lib/python3.[10](https://github.com/redacted/redacted/runs/redacted?check_suite_focus=true#step:4:11)/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 306, in ci
    with fix_head_if_github_action(metadata):
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 104, in fix_head_if_github_action
    checkout = subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'checkout', 'e85632dbaa90a3b5e150a4a9b39bd2367aee73ae']' returned non-zero exit status [12](https://github.com/redacted/redacted/runs/redacted?check_suite_focus=true#step:4:13)8.
Error: Process completed with exit code 2.
```

Looks like `git checkout` is also affected?

**Comment by arunkumar-telnyx** [comment]
Hi  @spencerdrak    I am also facing the same issue on most of the repos now. 

using 

```
   steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
```

Error
```
Run semgrep ci
Scan environment:
  versions    - semgrep 0.101.0 on python 3.10.5
  environment - running in environment github-actions, triggering event is pull_request
  semgrep.dev - authenticated as team
Fixing git state for github action pull request
Not on head ref: 0a2a0ad2ea131c4[6](https://github.com/team/infra/runs/7086714865?check_suite_focus=true#step:4:7)95[7](https://github.com/team/infra/runs//7086714865?check_suite_focus=true#step:4:8)c75d2[8](https://github.com/team/infra/runs//7086714865?check_suite_focus=true#step:4:9)35c6bc[9](https://github.com/team/infra/runs//7086714865?check_suite_focus=true#step:4:10)3b422869; checking that out now.
Command '['git', 'checkout', '0a2a0ad2ea131c46957c75d2835c6bc93b422869']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/usr/local/lib/python3.[10](https://github.com/team/infra/runs/7086714865?check_suite_focus=true#step:4:11)/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 306, in ci
    with fix_head_if_github_action(metadata):
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 104, in fix_head_if_github_action
    checkout = subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'checkout', '0a2a0ad2ea131c46957c75d2835c6bc93b422869']' returned non-zero exit status [12](https://github.com/team/infra/runs/7086714865?check_suite_focus=true#step:4:13)8.
Error: Process completed with exit code 2.
```
