### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by invidian** [semgrep/semgrep#5633]
**Describe the bug**
Unhandled exception:
```console
$ semgrep

Scanning across multiple languages:
    <multilang> | 3 rules × 549 files
             go | 4 rules ×  45 files

  100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|594/594 tasks
list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/semgrep/commands/scan.py", line 840, in scan
    output_handler.output(
  File "/usr/lib/python3.10/site-packages/semgrep/output.py", line 319, in output
    output = self._build_output()
  File "/usr/lib/python3.10/site-packages/semgrep/output.py", line 429, in _build_output
    return self.formatter.output(
  File "/usr/lib/python3.10/site-packages/semgrep/formatter/base.py", line 28, in output
    return self.format(
  File "/usr/lib/python3.10/site-packages/semgrep/formatter/text.py", line 479, in format
    findings_output.append("\nFindings:\n" + "\n".join(first_party_output))
  File "/usr/lib/python3.10/site-packages/semgrep/formatter/text.py", line 394, in _build_text_output
    yield from TextFormatter._finding_to_line(
  File "/usr/lib/python3.10/site-packages/semgrep/formatter/text.py", line 101, in _finding_to_line
    len(lines[0].rstrip()) - len(dedented_lines[0].rstrip())
IndexError: list index out of range
```

**To Reproduce**
```sh
git clone git@github.com:kubernetes-sigs/image-builder.git
cd image-builder
git checkout 85c19fdb7bd5c0daca47ac9d655b2efcdf4dda72
cat <<EOF > .semgrep.yml
rules:
  - id: bad-error-wrap-wording
    patterns:
      - pattern-regex: fmt\.Errorf\(".?([Ff]ailed|[]Uu]nable|[Cc]ould|([Ee]rror)|([Cc]an[ ]?not))
    message: Phrases "fail", "failed", "unable", "could not", "cannot", "can not" should not be used when wrapping errors. Use verb in continuous form instead!
    languages: [go]
    severity: ERROR
  - id: printed-messages-must-be-captialized
    patterns:
      - pattern-regex: (fmt.Print(ln|f)|\bt\.(Error|Fatal|Log)(|f))\("[a-z]
    message: Printed messages must be capitalized.
    languages: [go]
    severity: ERROR
  - id: strings-must-be-quoted-using-q
    patterns:
      - pattern-regex: "'%s'"
    message: When formatting, strings must be quoted using %q instead of e.g. '%s'.
    languages: [go]
    severity: ERROR
  - id: error-wrapping-must-be-preceded-by-space
    patterns:
      - pattern-regex: '[^ ]%w'
    message: When wrapping errors, %w must be preceded by space.
    languages: [go]
    severity: ERROR
  - id: files-must-not-have-trailing-whitespace
    patterns:
      - pattern-regex: '[[:blank:]]$'
    message: Files must not have any trailing whitespace.
    languages: [generic]
    severity: ERROR
  - id: files-must-not-have-trailing-newlines
    patterns:
      - pattern-regex: '\n\n\Z'
    message: Files must not have any trailing newlines.
    languages: [generic]
    severity: ERROR
  - id: all-lines-must-end-with-newline
    patterns:
      - pattern-regex: '\S\z'
    message: All lines must end with newline.
    languages: [generic]
    severity: ERROR
EOF
semgrep
```

**Expected behavior**

No unexpected exceptions are shown to the user.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
```
$ semgrep --version
0.100.0
```

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1569/list-index-out-of-range. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by vivekkhimani** [comment]
PR with the fix - https://github.com/returntocorp/semgrep/pull/5711
