### ISSUE TITLE
Regression - Inline join with taint not working anymore since 0.107

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#5839]
**Describe the bug**
Inline join with a taint rule do not work anymore in 0.107 as Semgrep produces an error on them:

```
missing field 'path' in JSON object of type 'Location'
Traceback (most recent call last):
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/commands/scan.py", line 814, in scan
    ) = semgrep.semgrep_main.main(
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 363, in main
    rule_matches_by_rule, semgrep_errors, all_targets, profiling_data = run_rules(
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 162, in run_rules
    join_rule_matches, join_rule_errors = join_rule.run_join_rule(
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/join_rule.py", line 535, in run_join_rule
    rule_matches = [
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/join_rule.py", line 557, in <listcomp>
    extra=core.CoreMatchExtra.from_json(match.get("extra", {})),
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/semgrep_interfaces/semgrep_output_v0.py", line 1385, in from_json
    dataflow_trace=CoreMatchDataflowTrace.from_json(x['dataflow_trace']) if 'dataflow_trace' in x else None,
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/semgrep_interfaces/semgrep_output_v0.py", line 1349, in from_json
    taint_source=Location.from_json(x['taint_source']) if 'taint_source' in x else None,
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/semgrep_interfaces/semgrep_output_v0.py", line 833, in from_json
    path=_atd_read_string(x['path']) if 'path' in x else _atd_missing_json_field('Location', 'path'),
  File "/usr/local/Cellar/semgrep/0.107.0/libexec/lib/python3.10/site-packages/semgrep/semgrep_interfaces/semgrep_output_v0.py", line 21, in _atd_missing_json_field
    raise ValueError(f"missing field '{json_field_name}'"
ValueError: missing field 'path' in JSON object of type 'Location'
```

**To reproduce**

Run the below rule

```
rules:
- id: inline-join-taint-regression
  severity: WARNING
  mode: join
  message: Regression in 0.107
  join:
    rules:
      - id: first
        languages: [php]
        mode: taint
        pattern-sources:
          - pattern: source(...)
        pattern-sinks:
          - pattern: sink($VAR)

      - id: second
        languages: [php]
        mode: taint
        pattern-sources:
          - pattern: sink($VAR)
        pattern-sinks:
          - pattern: sink2(...)
    on:
      - 'first.$VAR == second.$VAR'
```

Against the below PHP code

```
<?php

sink2(sink(source('aaa')));
```

Command used: `semgrep -c inline-join-taint.yml inline-join-taint.php`

**Expected behavior**
Semgrep should run the inline join rules

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep 0.107 on MacOSX (installed via `brew`)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1701/regression-inline-join-with-taint-not-working-anymore-since-0107. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
After some investigation with `git bisect` I concluded that this regression was introduced by #5765.
