### ISSUE TITLE
Getting error while running njsscan

### ISSUE THREAD

**Issue by spmishra121** [semgrep/semgrep#5969]
Hi @brendongo 
We are facing issue while running NJSScan at our end after updating the same. An issue regarding this is already open with NJSScan
 https://github.com/ajinabraham/njsscan/issues/95 (Check Comments with this).

To analyse more further, I had executed semgrep and njsscan individually. Please find the details below...

**Python Version: 3.7.10**

**[root@ip-10-25-48-63 workspace]# njsscan --version

**njsscan: v0.3.3 | Ajin Abraham | opensecurity.in**
[root@ip-10-25-48-63 workspace]#**

Result of njsscan
[root@ip-10-25-48-63 workspace]# njsscan .

Pattern Match ████████████████████████████████████████████████████████████ 134
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
ret[0] = function(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
**kwargs,
File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
deep,
File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
target_manager, filtered_rules, dump_command_for_core, deep
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
rules, target_manager, dump_command_for_core, deep
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
returncode = runner.execute()
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
rc = asyncio.run(self._stream_subprocess())
File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
preexec_fn=setrlimits_preexec_fn,
File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
stderr=stderr, **kwds)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
bufsize, **kwargs)
File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
self._child_watcher_callback, transp)
File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
"Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

Semantic Grep 19
Traceback (most recent call last):
File "/usr/local/bin/njsscan", line 8, in
sys.exit(main())
File "/usr/local/lib/python3.7/site-packages/njsscan/main.py", line 76, in main
args.config,
File "/usr/local/lib/python3.7/site-packages/njsscan/njsscan.py", line 44, in scan
result = scanner.scan()
File "/usr/local/lib/python3.7/site-packages/libsast/scanner.py", line 65, in scan
self.options).scan(valid_paths)
File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 41, in scan
self.format_output(sgrep_out)
File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 46, in format_output
self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable
Future exception was never retrieved
future:
Traceback (most recent call last):
File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
ret[0] = function(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
**kwargs,
File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
deep,
File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
target_manager, filtered_rules, dump_command_for_core, deep
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
rules, target_manager, dump_command_for_core, deep
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
returncode = runner.execute()
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
rc = asyncio.run(self._stream_subprocess())
File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
preexec_fn=setrlimits_preexec_fn,
File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
stderr=stderr, **kwds)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
bufsize, **kwargs)
File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
self._child_watcher_callback, transp)
File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
"Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib64/python3.7/asyncio/base_subprocess.py", line 171, in _connect_pipes
proc.stdout)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 1452, in connect_read_pipe
await waiter
concurrent.futures._base.CancelledError

**Semgrep Version:
Installing collected packages: semgrep
Attempting uninstall: semgrep
Found existing installation: semgrep 0.104.0
Uninstalling semgrep-0.104.0:
Successfully uninstalled semgrep-0.104.0
ERROR: libsast 1.5.2 requires semgrep==0.104.0, but you'll have semgrep 0.110.0 which is incompatible.
Successfully installed semgrep-0.110.0**
[root@ip-10-25-48-63 workspace]#

Semgrep Result

[root@ip-10-25-48-63 workspace]# semgrep --config=auto .
Fetching rules from https://semgrep.dev/registry.

Scanning across multiple languages:
| 55 rules × 330 files
ts | 196 rules × 132 files
json | 4 rules × 10 files
js | 185 rules × 4 files
bash | 5 rules × 3 files
dockerfile | 5 rules × 2 files

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|481/481 tasks

Findings:

seeder-scripts/default-collection-views/default-collection-views-seeder-scripts/Dockerfile
dockerfile.security.missing-user.missing-user
By not specifying a USER, a program in the container may run as 'root'. This is a security
hazard. If an attacker can control a process running as root, they may have control over the
container. Ensure that the last USER in a Dockerfile is a USER other than 'root'.
Details: https://sg.run/Gbvn

 18┆ CMD ["node", "default-collection-views-seeder.js"]
src/common/handlers/dlss/dlss.service.ts
javascript.express.security.audit.xss.direct-response-write.direct-response-write
Detected directly writing to a Response object from user-defined input. This bypasses any
HTML escaping and may expose your application to a Cross-Site-scripting (XSS) vulnerability.
Instead, use 'resp.render()' to render safely escaped HTML.
Details: https://sg.run/vzGl

139┆ return res.status(200).send(result);
  ⋮┆----------------------------------------
335┆ return res.status(200).send(result);
Some files were skipped or only partially analyzed.
Scan skipped: 14 files larger than 1.0 MB, 40428 files matching .semgrepignore patterns
For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1197 rules on 165 files: 3 findings.
[root@ip-10-25-48-63 workspace]#

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1812/getting-error-while-running-njsscan. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by spmishra121** [comment]
Hi @brendongo , We are looking resolution on this issue as our security gate is consistently failing.

**Comment by bmahe** [comment]
Hi @spmishra121 ,

Your execution trace of `semgrep --config=auto .` shows that semgrep is working without errors and showing some findings.
Do you have a reproducible error with semgrep?

**Comment by spmishra121** [comment]
@bmahe , When using semgrep version 0.104.0 (Which is used as latest version in njsscan 0.3.1). I am getting no error but when running njsscan. I am getting error.
@ajinabraham , Please provide your feedback on this ticket. Seems error is not because of semgrep. It is because of output type. For HTML report we are getting error while for json, there is no error.
