### ISSUE TITLE
ValueError PosixPath has an empty name when running test on single config

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#6107]
```
$ semgrep --test --config stacktrace-disclosure.yaml
PosixPath('.') has an empty name
Traceback (most recent call last):
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/commands/scan.py", line 746, in scan
    semgrep.test.test_main(
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/test.py", line 700, in test_main
    generate_test_results(
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/test.py", line 452, in generate_test_results
    config_test_filenames = get_config_test_filenames(config, config_filenames, target)
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/test.py", line 365, in get_config_test_filenames
    return {
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/test.py", line 366, in <dictcomp>
    config: [target for target in targets if target_matches_config(target, config)]
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/test.py", line 366, in <listcomp>
    config: [target for target in targets if target_matches_config(target, config)]
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/test.py", line 359, in target_matches_config
    or relatively_eq(original_target, target, original_config, config)
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/test.py", line 320, in relatively_eq
    rel2 = remove_all_suffixes(child2.relative_to(parent2))
  File "/usr/local/Cellar/semgrep/0.113.0/libexec/lib/python3.10/site-packages/semgrep/test.py", line 314, in remove_all_suffixes
    result = p.with_suffix("")
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 782, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: PosixPath('.') has an empty name
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1892/valueerror-posixpath-has-an-empty-name-when-running-test-on-single. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
@Sjord could you share `stacktrace-disclosure.yaml` or at least a sanitized / minimized version of it that exhibits the problem?

**Comment by Sjord** [comment]
I just copied [this one](https://github.com/returntocorp/semgrep-rules/blob/develop/csharp/lang/security/stacktrace-disclosure.yaml) to an empty directory, but I get this problem with any rule file. Can you reproduce it?

**Comment by IagoAbal** [comment]
Thanks, yep, I can reproduce it! Sorry, I had not tried it myself, but given the error it makes sense that this is not specific to any config.

**Comment by Sjord** [comment]
​

**Comment by IagoAbal** [comment]
cc @aryx maybe this is solved in the upcoming CLI written in OCaml?
