### ISSUE TITLE
Extract Mode: No such file or directory: '/tmp/extracted-xxxx'

### ISSUE THREAD

**Issue by 0xdbe** [semgrep/semgrep#6180]
**Describe the bug**

Semgrep can't retrieve extracted code:

```
[Errno 2] No such file or directory: '/tmp/extracted-19361-cc9555Ruby'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/semgrep/commands/scan.py", line 827, in scan
    ) = semgrep.semgrep_main.main(
  File "/usr/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 416, in main
    ) = run_rules(
  File "/usr/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 169, in run_rules
    ) = core_runner.invoke_semgrep(
  File "/usr/lib/python3.10/site-packages/semgrep/core_runner.py", line 939, in invoke_semgrep
    ) = self._run_rules_direct_to_semgrep_core(
  File "/usr/lib/python3.10/site-packages/semgrep/core_runner.py", line 873, in _run_rules_direct_to_semgrep_core
    self._add_match_times(profiling_data, core_output.time)
  File "/usr/lib/python3.10/site-packages/semgrep/core_runner.py", line 661, in _add_match_times
    profiling_data.set_file_times(Path(t.path), rule_timings, t.run_time)
  File "/usr/lib/python3.10/site-packages/semgrep/profiling.py", line 90, in set_file_times
    num_bytes = target.stat().st_size
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extracted-19361-cc9555Ruby'
```

**To Reproduce**

- Create a rule to extract ruby from ERB Template:

```
rules:
  - id: extract-ruby-from-erb
    languages:
      - generic
    paths:
      include:
        - "*.erb"
    pattern: <% $...RUBY %>
    mode: extract
    dest-language: ruby
    extract: $...RUBY
```

- Start container (using fish)

```
docker run --rm \
  -v "$PWD/src:/src" \
  -v "$PWD/rules/:/rules" \
  returntocorp/semgrep semgrep --config=/rules
``` 

**Expected behavior**
parse extracted code.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
- Semgrep 0.111.1-1 on Arch linux (installed from AUR)
- Semgrep 0.114.0 on Arch linux (edit package build from AUR to install tnhe latest release)
- Docker: Semgrep 0.114.0

**Use case**
I'm trying to check ERB files, use by Ruby on Rails to produce HTML pages.
ERB file is a mix of HTML, Ruby and Javascript.
Extract Ruby code from ERB template allows to re-use ruby rules.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1923/extract-mode-no-such-file-or-directory-tmpextracted-xxxx. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by 0xdbe** [comment]
A way to reproduce:

- Clone https://github.com/discourse/discourse

- Run Semgrep

```
semgrep \
  --config=~/Code/semgrep-rules/generic/erb/extract-ruby-from-erb.yaml \
  --config "p/ruby"
```

```
Scanning across multiple languages:
           ruby | 19 rules × 3896 files
    <multilang> |  1 rule  ×  143 files

   99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   |6757/6855 tasks
[Errno 2] No such file or directory: '/tmp/extracted-70074-092f72Ruby'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/semgrep/commands/scan.py", line 828, in scan
    ) = semgrep.semgrep_main.main(
  File "/usr/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 424, in main
    ) = run_rules(
  File "/usr/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 170, in run_rules
    ) = core_runner.invoke_semgrep(
  File "/usr/lib/python3.10/site-packages/semgrep/core_runner.py", line 939, in invoke_semgrep
    ) = self._run_rules_direct_to_semgrep_core(
  File "/usr/lib/python3.10/site-packages/semgrep/core_runner.py", line 873, in _run_rules_direct_to_semgrep_core
    self._add_match_times(profiling_data, core_output.time)
  File "/usr/lib/python3.10/site-packages/semgrep/core_runner.py", line 661, in _add_match_times
    profiling_data.set_file_times(Path(t.path), rule_timings, t.run_time)
  File "/usr/lib/python3.10/site-packages/semgrep/profiling.py", line 90, in set_file_times
    num_bytes = target.stat().st_size
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/extracted-70074-092f72Ruby'
```

This error happens with large project and many rules.

**Comment by aryx** [comment]
I actually get another error (on my Arch Linux machine): 
```
(cli) [pad@thinkstation discourse (main)]$ semgrep --config=~/extract-ruby-from-erb.yaml --config "p/ruby" 
Semgrep rule registry URL is https://semgrep.dev/registry.

Scanning across multiple languages:
           ruby | 19 rules × 3903 files
    <multilang> |  1 rule  ×  143 files

    0%|                                                                                                                                                                                                       |0/5045 tasks
[ERROR] Fatal error at line :1:
 (Sys_error "/tmp/extracted-1564257-bf43f5Ruby: Too many open files")
====[ BEGIN error trace ]====
(Sys_error "/tmp/extracted-1564257-bf43f5Ruby: Too many open files")
Raised by primitive operation at Stdlib__Filename.temp_file.try_name in file "filename.ml", line 345, characters 16-75
Re-raised at Stdlib__Filename.temp_file.try_name in file "filename.ml", line 348, characters 30-37
Called from Common.new_temp_file in file "src/pfff/commons/Common.ml", line 1483, characters 17-75
Called from Match_extract_mode.mk_extract_target in file "src/engine/Match_extract_mode.ml", line 120, characters 27-68
Called from Match_extract_mode.extract_as_separate.(fun) in file "src/engine/Match_extract_mode.ml", line 379, characters 26-70
Called from Stdlib__List.filter_map.aux in file "list.ml", line 258, characters 14-17
Called from Match_extract_mode.extract_nested_lang in file "src/engine/Match_extract_mode.ml", line 427, characters 4-69
Called from Run_semgrep.extract_targets_of_config.(fun) in file "src/runner/Run_semgrep.ml", line 544, characters 8-174
Called from Stdlib__List.concat_map.aux in file "list.ml", line 268, characters 16-19
Called from Run_semgrep.extract_targets_of_config in file "src/runner/Run_semgrep.ml", line 536, characters 2-748
Called from Run_semgrep.semgrep_with_rules in file "src/runner/Run_semgrep.ml", line 593, characters 4-59
Called from Run_semgrep.semgrep_with_raw_results_and_exn_handler in file "src/runner/Run_semgrep.ml", line 691, characters 21-58
=====[ END error trace ]=====
```

**Comment by aryx** [comment]
Ok I've fixed a first bug, and now I'm able to reproduce your error.

**Comment by aryx** [comment]
I think I understand why. It's because the extracted content from the .erb files generates some parse errors,
and while we convert matching to the extracted content to the original file, we don't do it for parse errors.

More generally, using extract mode for ERB might be more complicated than anticipated because the resulting code
must be parsable by Ruby, but each <? xxx ?> can be any Ruby code, including partial expressions or statements, and
so this does not work well with how extract-mode is designed.

**Comment by aryx** [comment]
There is a `reduce: concat` special field that you can add in an extract mode rule, to concatenerate together
all the elements that were extracted, hoping to generate something that would parse, but I don't think it would
be enough here for the .ERB.

**Comment by 0xdbe** [comment]
is there any update on this issue ?

**Comment by aryx** [comment]
It's on our radar but unfortunately we have very few resources lately. Extract mode is part of our roadmap, and we think it's a cool feature, but it's just lower priority than other stuff right now.
Sorry ...
