### ISSUE TITLE
Error while running on an Android project

### ISSUE THREAD

**Issue by twittemb** [semgrep/semgrep#6249]
**Describe the bug**

I have an issue while running Mobsfscan (which relies on semgrep) on an Android/Kotlin project with the following error.

Environment:

macOS Monterey
proc M1 Ultra
Python 3.8.9 (default, May 17 2022, 12:55:41) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
mobsfscan: v0.1.1

the stack trace seems to incriminate semgrep :-(

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/common.py", line 45, in myrunner
    ret[0] = function(*args, **kwargs)
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/core_sgrep/helpers.py", line 50, in invoke_semgrep
    ) = semgrep_main.main(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/semgrep_main.py", line 363, in main
    rule_matches_by_rule, semgrep_errors, all_targets, profiling_data = run_rules(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/semgrep_main.py", line 154, in run_rules
    ) = core_runner.invoke_semgrep(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/core_runner.py", line 758, in invoke_semgrep
    ) = self._run_rules_direct_to_semgrep_core(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
    returncode = runner.execute()
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/core_runner.py", line 283, in execute
    rc = asyncio.run(self._stream_subprocess())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/semgrep/core_runner.py", line 257, in _stream_subprocess
    raise SemgrepError(f"Error while running rules: {r}")
semgrep.error.SemgrepError: Error while running rules: 0 bytes read on a total of 2 expected bytes
- Semantic Grep  5
Traceback (most recent call last):
  File "/Users/xxx/Library/Python/3.8/bin/mobsfscan", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/mobsfscan/__main__.py", line 65, in main
    scan_results = MobSFScan(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/mobsfscan/mobsfscan.py", line 79, in scan
    result = scanner.scan()
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/scanner.py", line 64, in scan
    results['semantic_grep'] = SemanticGrep(
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 41, in scan
    self.format_output(sgrep_out)
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 46, in format_output
    self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable

```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Running Mobsfscan on macOS Monterey

**Use case**
being able to run a Mobsfscan analysis on my android projects.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1962/error-while-running-on-an-android-project. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ievans** [comment]
@ajinabraham any ideas?

**Comment by ajinabraham** [comment]
@ievans The exception comes from semgrep. We saw this from multiple semgrep versions. Anything wrong with the integration?


https://github.com/ajinabraham/libsast/blob/ab406dcc45319d133e296d8594b8aff035036d71/libsast/core_sgrep/helpers.py#L9

**Comment by ievans** [comment]
I'm puzzled by it, epecially since the issue only seems to appear when Semgrep is wrapped as a subprocess. Do you know how often this issue is occurring for users at all?

**Comment by ajinabraham** [comment]
I think we had one reported in the repo and a few mentions in the slack channel.

**Comment by emjin** [comment]
Hi @twittemb! Thanks for filing this. I don't know what rules `mobsfscan` uses, but can you try running `semgrep --config p/default` on the repository with an error? If that works (aka gives the same error), can you add `--debug` and share the output?

**Comment by emjin** [comment]
@ajinabraham If you have a reproduction, could you also send the `--debug` output?

**Comment by ajinabraham** [comment]
The rules we use are validated against latest semgrep https://github.com/MobSF/mobsfscan/blob/9bef3983eb13051b2162626717eeaed96c3fbbd7/.github/workflows/tests.yml#L39

I don’t have a test case to reproduce the above. maybe the author can help.
