### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by savetree** [semgrep/semgrep#6678]
I caught a blocking error in 1.1.0:

```
root@wopr:~/SOURCE# semgrep scan --config auto
Semgrep rule registry URL is https://semgrep.dev/registry.

Scanning across multiple languages:
    <multilang> |  71 rules × 6844 files
           java | 107 rules × 2580 files
           bash |   4 rules ×   26 files
             js | 171 rules ×    4 files
           html |   1 rule  ×    3 files
           json |   4 rules ×    1 file 

  100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|9458/9458 tasks
unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/commands/scan.py", line 856, in scan
    baseline_commit=baseline_commit,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/semgrep_main.py", line 440, in main
    deep,
  File "/usr/local/lib/python3.7/dist-packages/semgrep/semgrep_main.py", line 171, in run_rules
    target_manager, rest_of_the_rules, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 1007, in invoke_semgrep
    rules, target_manager, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 976, in _run_rules_direct_to_semgrep_core
    raise e
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 959, in _run_rules_direct_to_semgrep_core
    rules, target_manager, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_runner.py", line 900, in _run_rules_direct_to_semgrep_core_helper
    outputs = core_matches_to_rule_matches(rules, core_output)
  File "/usr/local/lib/python3.7/dist-packages/semgrep/core_output.py", line 205, in core_matches_to_rule_matches
    if rule_match.cli_unique_key in seen_cli_unique_keys:
  File "<string>", line 2, in __hash__
TypeError: unhashable type: 'list'
```

**Comment by aryx** [comment]
I'm not able to reproduce locally (when running semgrep on the semgrep repo itself).
Can you make a simple minimal reproducible case?

**Comment by dvolvox** [comment]
I'm having the same issue. I'm trying to scan a JAVA based project:

[]$ semgrep scan --config auto -l JAVA ./PROJECT/
/usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Semgrep rule registry URL is https://semgrep.dev/registry.

Scanning across multiple languages:
    <multilang> |  71 rules × 33532 files
           java | 107 rules ×  3750 files
             ts | 181 rules ×  2074 files
           html |   1 rule  ×   376 files
           json |   4 rules ×   226 files
             js | 171 rules ×   168 files

  100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|40126/40126 tasks
unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/semgrep/commands/scan.py", line 856, in scan
    baseline_commit=baseline_commit,
  File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 440, in main
    deep,
  File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 171, in run_rules
    target_manager, rest_of_the_rules, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 1007, in invoke_semgrep
    rules, target_manager, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 976, in _run_rules_direct_to_semgrep_core
    raise e
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 959, in _run_rules_direct_to_semgrep_core
    rules, target_manager, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 900, in _run_rules_direct_to_semgrep_core_helper
    outputs = core_matches_to_rule_matches(rules, core_output)
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_output.py", line 205, in core_matches_to_rule_matches
    if rule_match.cli_unique_key in seen_cli_unique_keys:
  File "<string>", line 3, in __hash__
TypeError: unhashable type: 'list'


What details do you require? 

Thank you.

**Comment by aryx** [comment]
Ideally a link to a toy repository or simple file showing the issue.

**Comment by akhercha** [comment]
Hey,
Digging this up but I have a similar issue at the moment.

I think this is replicable;
```sh
git clone https://github.com/akhercha/satoru
cd satoru
git checkout feat/log_data_indexes
semgrep --config https://github.com/avnu-labs/semgrep-cairo-rules/releases/download/v0.0.1/cairo-rules.yaml ./src
```

Would give:
```sh
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 129 files (only git-tracked) with 2 Code rules:

  CODE RULES
  Scanning 129 files with 2 cairo rules.

  SUPPLY CHAIN RULES

  💎 Sign in with `semgrep login` and run
     `semgrep ci` to find dependency vulnerabilities and
     advanced cross-file findings.


  PROGRESS

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺  98% 0:00:00                                                                                               
unhashable type: 'list'
Traceback (most recent call last):
  File "/home/akhercha/.pyenv/versions/3.10.13/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/home/akhercha/.pyenv/versions/3.10.13/lib/python3.10/site-packages/semgrep/commands/scan.py", line 614, in scan
    ) = semgrep.run_scan.run_scan(
  File "/home/akhercha/.pyenv/versions/3.10.13/lib/python3.10/site-packages/semgrep/run_scan.py", line 519, in run_scan
    ) = run_rules(
  File "/home/akhercha/.pyenv/versions/3.10.13/lib/python3.10/site-packages/semgrep/run_scan.py", line 213, in run_rules
    join_rule_matches, join_rule_errors = join_rule.run_join_rule(
  File "/home/akhercha/.pyenv/versions/3.10.13/lib/python3.10/site-packages/semgrep/join_rule.py", line 519, in run_join_rule
    ERROR_MAP[error_dict.get(errortype)].from_dict(error_dict)
TypeError: unhashable type: 'list'
```

Let me know if you need more infos - or if I should create another issue.
Thanks!
