### ISSUE TITLE
FileNotFoundError on symbolic link that points to non-existing file

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#6890]
My repository has a broken symlink. Semgrep gives a FileNotFoundError. The file indeed cannot be found, but it would be nice if semgrep just ignores this file and keeps scanning.

This currently breaks the scanning for a project for us, so it has fairly high priority to us.

```
$ semgrep ci --baseline-commit somehexcommit --config "p/r2c-security-audit"
Running `semgrep ci` without API token but with configs ('p/r2c-security-audit',)
Scan environment:
  versions    - semgrep 1.4.0 on python 3.11.1
  environment - running in environment git, triggering event is unknown

Fetching configuration from semgrep.dev
Semgrep rule registry URL is https://semgrep.dev/registry.
[Errno 2] No such file or directory: 'ansible/roles/provision_redacted/files/mysql.c'
Traceback (most recent call last):
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/commands/ci.py", line 381, in ci
    ) = semgrep.semgrep_main.main(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/semgrep_main.py", line 437, in main
    ) = run_rules(
        ^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/semgrep_main.py", line 170, in run_rules
    ) = core_runner.invoke_semgrep(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/core_runner.py", line 1018, in invoke_semgrep
    ) = self._run_rules_direct_to_semgrep_core(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/core_runner.py", line 988, in _run_rules_direct_to_semgrep_core
    raise e
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/core_runner.py", line 970, in _run_rules_direct_to_semgrep_core
    return self._run_rules_direct_to_semgrep_core_helper(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/core_runner.py", line 771, in _run_rules_direct_to_semgrep_core_helper
    plan = self._plan_core_run(rules, target_manager, all_targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/core_runner.py", line 704, in _plan_core_run
    target_manager.get_files_for_rule(
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/target_manager.py", line 727, in get_files_for_rule
    paths = self.get_files_for_language(lang)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/target_manager.py", line 685, in get_files_for_language
    files = self.filter_by_size(self.max_target_bytes, candidates=files.kept)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/target_manager.py", line 648, in filter_by_size
    kept, removed = partition(
                    ^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/boltons/iterutils.py", line 699, in partition
    bucketized = bucketize(src, key)
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/boltons/iterutils.py", line 674, in bucketize
    key_of_val = key_func(val)
                 ^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.4.0/libexec/lib/python3.11/site-packages/semgrep/target_manager.py", line 649, in <lambda>
    candidates, lambda path: os.path.getsize(path) <= max_target_bytes
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 50, in getsize
FileNotFoundError: [Errno 2] No such file or directory: 'ansible/roles/provision_redacted/files/mysql.c'
```

```
$ ls -l ansible/roles/provision_redacted/files/mysql.c
lrwxr-xr-x  1 sjoerdlangkemper  staff  48 Jan 19 10:06 ansible/roles/provision_redacted/files/mysql.c -> ../../../../.docker/non-existing/mysql.c
```

**Comment by Sjord** [comment]
> This currently breaks the scanning for a project for us, so it has fairly high priority to us.

Could you assign this medium priority, please?

**Comment by IagoAbal** [comment]
Can this be reproduced with `semgrep scan` or does it only affect `semgrep ci`?

**Comment by IagoAbal** [comment]
@Sjord could you please confirm if 1.22.0 fixes the issue for you?
