### ISSUE TITLE
proc/12142/net/sockstat no such file error

### ISSUE THREAD

**Issue by Hedyt** [semgrep/semgrep#7098]
Semgrep rule registry URL is https://semgrep.dev/registry.
[Errno 2] No such file or directory: 'proc/12142/net/sockstat'
Traceback (most recent call last):
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/commands/scan.py", line 856, in scan
    baseline_commit=baseline_commit,
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 443, in main
    deep,
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 171, in run_rules
    target_manager, rest_of_the_rules, dump_command_for_core, deep
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/core_runner.py", line 1009, in invoke_semgrep
    rules, target_manager, dump_command_for_core, deep
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/core_runner.py", line 978, in _run_rules_direct_to_semgrep_core
    raise e
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/core_runner.py", line 961, in _run_rules_direct_to_semgrep_core
    rules, target_manager, dump_command_for_core, deep
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/core_runner.py", line 770, in _run_rules_direct_to_semgrep_core_helper
    plan = self._plan_core_run(rules, target_manager, all_targets)
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/core_runner.py", line 704, in _plan_core_run
    language, rule.includes, rule.excludes, rule.id
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/target_manager.py", line 727, in get_files_for_rule
    paths = self.get_files_for_language(lang)
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/target_manager.py", line 685, in get_files_for_language
    files = self.filter_by_size(self.max_target_bytes, candidates=files.kept)
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/target_manager.py", line 649, in filter_by_size
    candidates, lambda path: os.path.getsize(path) <= max_target_bytes
  File "/tutorial-env/lib/python3.7/site-packages/boltons/iterutils.py", line 699, in partition
    bucketized = bucketize(src, key)
  File "/tutorial-env/lib/python3.7/site-packages/boltons/iterutils.py", line 674, in bucketize
    key_of_val = key_func(val)
  File "/tutorial-env/lib/python3.7/site-packages/semgrep/target_manager.py", line 649, in <lambda>
    candidates, lambda path: os.path.getsize(path) <= max_target_bytes
  File "/usr/local/python3/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'proc/12142/net/sockstat'

**Comment by aryx** [comment]
Which version of semgrep are you using, which OS?
