### ISSUE TITLE
Semgrep isn't thread-safe when reading/writing the default configuration file

### ISSUE THREAD

**Issue by christophetd** [semgrep/semgrep#7102]
## Description 

While using Semgrep with https://github.com/DataDog/guarddog/, we noticed that it isn't thread-safe. In particular, that seems to be due to how the configuration file `$HOME/.semgrep/settings.yml` is read and written.

## Reproduction

Below is a sample piece of code which runs Semgrep in parallel with 10 worker threads. 

```python
import concurrent.futures
from pathlib import Path

from semgrep import semgrep_main
from concurrent.futures import ThreadPoolExecutor


def do_work():
    return semgrep_main.invoke_semgrep(Path("/tmp/rule.yml"), [Path("/tmp/code.js")])


# Write sample rule
with open("/tmp/rule.yml", "w") as f:
    f.write("""
rules:
  - id: my-rule
    pattern: foo(...)
    message: "You are using foo()"
    languages: [javascript]
    severity: ERROR
""")


# Write sample source code
with open("/tmp/code.js", "w") as f:
    f.write("""
foo("hello world!")    
""")

futures = []
with ThreadPoolExecutor(max_workers=10) as pool:
    for i in range(100):
        futures.append(pool.submit(do_work))

    for completed_future in concurrent.futures.as_completed(futures):
        print(completed_future.result())
```

Output (with semgrep  1.9.0) - I show a few outputs as it's non-deterministic due to this very bug.

```bash
$ rm -f $HOME/.semgrep/settings.yml
$ python repro.py
Traceback (most recent call last):
  File "/Users/christophe.tafanidereeper/workspace/guarddog/semgrep-repro.py", line 36, in <module>
    print(completed_future.result())
...
  File "/Users/christophe.tafanidereeper/workspace/guarddog/venv/lib/python3.10/site-packages/ruamel/yaml/emitter.py", line 398, in expect_document_end
    raise EmitterError(
ruamel.yaml.emitter.EmitterError: expected DocumentEndEvent, but got DocumentStartEvent()

$ cat $HOME/.semgrep/settings.yml # empty
$  rm -f $HOME/.semgrep/settings.yml
$ python repro.py
Traceback (most recent call last):
  File "/Users/christophe.tafanidereeper/workspace/guarddog/semgrep-repro.py", line 36, in <module>
    print(completed_future.result())
...
  File "/Users/christophe.tafanidereeper/workspace/guarddog/venv/lib/python3.10/site-packages/ruamel/yaml/emitter.py", line 1255, in flush_stream
    self.stream.flush()
ValueError: I/O operation on closed file.


$ cat $HOME/.semgrep/settings.yml # empty
```

Let's try with a sample initial valid Semgrep config:

```bash
$ cat > $HOME/.semgrep/settings.yml <<EOF
anonymous_user_id: 5df99efc-5a11-412f-9651-8880e0b181c1
EOF
$ python repro.py
Bad settings format; /Users/christophe.tafanidereeper/.semgrep/settings.yml will be overriden. Contents:
None
Traceback (most recent call last):
  File "/Users/christophe.tafanidereeper/workspace/guarddog/semgrep-repro.py", line 36, in <module>
    print(completed_future.result())
  ...
  File "/Users/christophe.tafanidereeper/workspace/guarddog/venv/lib/python3.10/site-packages/ruamel/yaml/emitter.py", line 398, in expect_document_end
    raise EmitterError(
ruamel.yaml.emitter.EmitterError: expected DocumentEndEvent, but got DocumentStartEvent()
```

**Proof that this is due to parallelism**: If we reduce the parallelism to 1, everything works fine.

```python
with ThreadPoolExecutor(max_workers=1) as pool:
```

Output:

```
$ rm -f $HOME/.semgrep/settings.yml
$ python repro.py
{'errors': [], 'paths': {'_comment': '<add --verbose for a list of skipped paths>', 'scanned': []}, 'results': [{'check_id': 'tmp.my-rule', 'end': {'col': 20, 'line': 2, 'offset': 20}, 'extra': {'engine_kind': 'OSSMatch', 'fingerprint': '6b331598756b210845d5cf63ebdb9de50dbe1293c6122adbc37c75fbc92307a61df2da8cb208d145541517035d77698ec5051ae7a42286be9d1f6686b2774495_0', 'is_ignored': False, 'lines': 'foo("hello world!")', 'message': 'You are using foo()', 'metadata': {}, 'metavars': {}, 'severity': 'ERROR'}, 'path': '/tmp/code.js', 'start': {'col': 1, 'line': 2, 'offset': 1}}], 'version': '1.9.0'}
{'errors': [], 'paths': {'_comment': '<add --verbose for a list of skipped paths>', 'scanned': []}, 'results': [{'check_id': 'tmp.my-rule', 'end': {'col': 20, 'line': 2, 'offset': 20}, 'extra': {'engine_kind': 'OSSMatch', 'fingerprint': '6b331598756b210845d5cf63ebdb9de50dbe1293c6122adbc37c75fbc92307a61df2da8cb208d145541517035d77698ec5051ae7a42286be9d1f6686b2774495_0', 'is_ignored': False, 'lines': 'foo("hello world!")', 'message': 'You are using foo()', 'metadata': {}, 'metavars': {}, 'severity': 'ERROR'}, 'path': '/tmp/code.js', 'start': {'col': 1, 'line': 2, 'offset': 1}}], 'version': '1.9.0'}
...
```

Similarly, if we keep a parallelism of 10 and we hook `semgrep.settings.Settings` to make sure it's thread-safe, we get the expected results:

```python
# NOTE: Obviously this is a terrible solution but it's just to make a point


def hook(function, pre_function, post_function):
    @functools.wraps(function)
    def run(*args, **kwargs):
        try:
            pre_function(*args, **kwargs)
            return function(*args, **kwargs)
        finally:
            post_function(*args, **kwargs)
    return run


def make_thread_safe(function):
    lock = threading.Lock()

    def pre_hook(*args, **kwargs):
        lock.acquire()

    def post_hook(*args, **kwargs):
        lock.release()

    return hook(function, pre_hook, post_hook)


semgrep.settings.Settings.__init__ = make_thread_safe(semgrep.settings.Settings.__init__)
```

## Expected behavior

Semgrep should be thread-safe

## Priority

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

As is, we unfortunately can't properly use Semgrep in parallel in GuardDog, leading  to slow scan times.

## Environment

* Semgrep v1.9.0
* Python 3.10.9

## Use case

GuardDog (https://github.com/DataDog/guarddog/) has a `verify` commands which scans a project dependencies (`requirements.txt`). We can't make it faster by running in parallel due to this issue.

**Comment by aryx** [comment]
Some discussions here: https://semgrep.slack.com/archives/C0242656NQ2/p1675867691144829

**Comment by christophetd** [comment]
not stale

**Comment by christophetd** [comment]
not stale

**Comment by aryx** [comment]
I think this might be fixed in osemgrep, our futur iteration of semgrep written fully in OCaml.
See https://github.com/returntocorp/semgrep/blob/develop/src/osemgrep/configuring/Semgrep_settings.ml#L122
