### ISSUE TITLE
No module found: resource (ModuelNotFoundError)

### ISSUE THREAD

**Issue by mai1x9** [semgrep/semgrep#7146]
When below command is run
```
semgrep -e '$X == $X' --lang=py app.py
semgrep --config auto
```

both the commands when run, the program throws error,
```
c:\users\mahi\appdata\local\programs\python\python38\lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "c:\users\mahi\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\mahi\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mahi\AppData\Local\Programs\Python\Python38\Scripts\semgrep.exe\__main__.py", line 4, in <module>
  File "c:\users\mahi\appdata\local\programs\python\python38\lib\site-packages\semgrep\__main__.py", line 4, in <module>
    from semgrep.cli import cli
  File "c:\users\mahi\appdata\local\programs\python\python38\lib\site-packages\semgrep\cli.py", line 8, in <module>
    from semgrep.commands.ci import ci
  File "c:\users\mahi\appdata\local\programs\python\python38\lib\site-packages\semgrep\commands\ci.py", line 18, in <module>
    import semgrep.semgrep_main
  File "c:\users\mahi\appdata\local\programs\python\python38\lib\site-packages\semgrep\semgrep_main.py", line 25, in <module>
    from semgrep.core_runner import CoreRunner
  File "c:\users\mahi\appdata\local\programs\python\python38\lib\site-packages\semgrep\core_runner.py", line 6, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

```

**Python Version Used:**
- python3.8.
- semgrep version: 1.12.0

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
- Windows 10 Operating system, installed using `pip install semgrep`

**Use case**
- Run semgrep to find potential dangerous patterns in the project and help fixing them. 
- Also helps semgrep to fix the bug and reduce issues to end users.

**Comment by mai1x9** [comment]
**My bad it looks like it does not work for Windows OS. I did like if `pip install semgrep` on windows would actually fail to run, instead of installing the package, to avoid confusion.**
