### ISSUE TITLE
JSON output format: local variable 'taint_sink' where it is not associated with a value

### ISSUE THREAD

**Issue by Gby56** [semgrep/semgrep#7288]
Hi ! I got an error on that exact line (more or less, the develop branch might be different already)
```
cannot access local variable 'taint_sink' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/commands/scan.py", line 937, in scan
    output_handler.output(
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/output.py", line 366, in output
    output = self._build_output()
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/output.py", line 493, in _build_output
    return self.formatter.output(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/formatter/base.py", line 29, in output
    return self.format(
           ^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/formatter/json.py", line 68, in format
    results=[
            ^
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/formatter/json.py", line 69, in <listcomp>
    self._rule_match_to_CliMatch(rule_match) for rule_match in rule_matches
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/formatter/json.py", line 32, in _rule_match_to_CliMatch
    dataflow_trace=rule_match.dataflow_trace,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/semgrep/1.13.0/libexec/lib/python3.11/site-packages/semgrep/rule_match.py", line 375, in dataflow_trace
    taint_sink=taint_sink,
               ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'taint_sink' where it is not associated with a value
```

https://github.com/returntocorp/semgrep/blob/4123c5eaa5159f2139dd6e2d0fe7e2a65ed03658/cli/src/semgrep/rule_match.py#L423

**Comment by Gby56** [comment]
Could this be linked to `--dataflow-traces` ? I haven't enabled it, but maybe it is by default for JSON output ?

**Comment by IagoAbal** [comment]
Hi @Gby56 and thanks for reporting this! Dataflow traces are always included in the JSON output IIRC. Would you be able to provide a way to reproduce this? I think it's not strictly needed for this error but it's always useful.

**Comment by nmote** [comment]
It seems likely that this is related to #6574, which only initializes the local `taint_sink` variable in `rule_match.py` if a certain condition is met, but attempts to use it either way. It must be rare for this branch to be taken, but it's clearly possible.

**Comment by Gby56** [comment]
FYI I'm not using deep semgrep, but maybe dataflows are also generated for the classic semgrep findings?

**Comment by brandonspark** [comment]
Hi @Gby56, thanks for reporting!

Yeah, dataflow traces will be present in the JSON output even if not explicitly requested via CLI, so you could run into this error anyways.

This PR should fix the issue: https://github.com/returntocorp/semgrep/pull/7299

**Comment by IagoAbal** [comment]
> FYI I'm not using deep semgrep, but maybe dataflows are also generated for the classic semgrep findings?

`--dataflow-traces`

**Comment by Gby56** [comment]
Thanks a lot @brandonspark :) that was definitely a an edge-case yeah, glad my weird repos could trigger it !

**Comment by IagoAbal** [comment]
@Gby56 could you please check if the Docker image `returntocorp:pr-7299` fixes the issue?

**Comment by Gby56** [comment]
@IagoAbal I've been trying to reproduce this, but no luck... I think the repository it was scanning might have some big javascript bundles, which could be pretty annoying

**Comment by IagoAbal** [comment]
> @IagoAbal I've been trying to reproduce this, but no luck... I think the repository it was scanning might have some big javascript bundles, which could be pretty annoying

Thanks for trying anyways!
