### ISSUE TITLE
 semgrep scan --test not working for version 1.28.0

### ISSUE THREAD

**Issue by sebasrevuelta** [semgrep/semgrep#8120]
**Describe the bug**
Next command:  `semgrep scan --test --config ./rules/ tests`
is showing the next error:

```
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/semgrep/commands/scan.py", line 822, in scan
    semgrep.test.test_main(
  File "/opt/homebrew/lib/python3.11/site-packages/semgrep/test.py", line 705, in test_main
    generate_test_results(
  File "/opt/homebrew/lib/python3.11/site-packages/semgrep/test.py", line 481,
```

**To Reproduce**
Execute: `semgrep scan --test --config ./rules/ tests`
where: rules is a folder with at least one yaml rule file and tests is the folder with a source code file to test the rule

**Expected behavior**
That it worked as previous version 1.27.0:

```
semgrep scan --test --config ./rules/ tests 
1/1: ✓ All tests passed 
No tests for fixes found.

semgrep --version
1.27.0
```

**Screenshots**

**What is the priority of the bug to you?**

P2

**Environment**
running locally in my mac: Apple M1 Pro

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/semgrep/issue/PA-2885/semgrep-scan-test-not-working-for-version-1280. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by hex0punk** [comment]
getting the same on an M1 Pro as well

**Comment by hex0punk** [comment]
seeing the same in 1.29.0

**Comment by mschwager** [comment]
I'm seeing this in CI as well. It appears to be Mac only, the Linux CI jobs are still passing.

**Comment by rouge8** [comment]
Still broken in 1.30.0

**Comment by GrosQuildu** [comment]
Still broken in 1.32.0. I am on MacOS (intel CPU)

**Comment by nophlyzone** [comment]
Issue is persisting on [1.34.1](https://semgrep.slack.com/archives/CK86BJ5DW/p1690981550584069).

**Comment by Matthewbialek** [comment]
Can confirm that issue is present in 1.34.1 , when was the last stable version for testing ?

**Comment by 0xdea** [comment]
Looks like it's solved in 1.36.0 (macOS ventura Intel).

**Comment by mschwager** [comment]
This appears to be fixed. Feel free to close 👍
