### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by rakeshmane** [semgrep/semgrep#8256]
I am unable to scan a repo due to the unicode error which crashes the semgrep before finishing the scan. Below is output generated by semgrep:

```
$ semgrep ci --output result.json  --json


┌────────────────┐
│ Debugging Info │
└────────────────┘

  SCAN ENVIRONMENT
  versions    - semgrep 1.31.2 on python 3.9.2
  environment - running in environment git, triggering event is unknown

  CONNECTION
  Reporting start of scan for XXXXXXX
  Fetching configuration from Semgrep Cloud Platform


  ENGINE
  Using Semgrep Pro Version: 1f0c85a
  Installed at /home/XXXXXXX/.local/lib/python3.9/site-packages/semgrep/bin/semgrep-core-proprietary


┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1311 files tracked by git with 1591 Code rules, 1787 Supply Chain rules, 513 Pro rules:


  CODE RULES

  Language      Rules   Files          Origin      Rules
 ─────────────────────────────        ───────────────────
  <multilang>      61    3834          Community    1078
  yaml             28     845          Pro rules     513
  php              60     144
  json              4      36
  bash              4      22
  python          356      18
  dockerfile        4      18
  terraform        99       1


  SUPPLY CHAIN RULES

  Ecosystem   Rules   Files   Lockfiles
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Pypi         1787     899   XXXXXXX/requirements.txt,
                              XXXXXXX/requirements.txt

  Analysis       Rules
 ──────────────────────
  Basic           1664
  Reachability     123

Semgrep Pro Engine may be slower and show different results than Semgrep OSS.
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━  94% 0:01:25
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/home/XXXXXXX/.local/lib/python3.9/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/home/XXXXXXX/.local/lib/python3.9/site-packages/semgrep/commands/ci.py", line 372, in ci
    ) = semgrep.semgrep_main.main(
  File "/home/XXXXXXX/.local/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 531, in main
    ) = run_rules(
  File "/home/XXXXXXX/.local/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 289, in run_rules
    ) = generate_unreachable_sca_findings(
  File "/home/XXXXXXX/.local/lib/python3.9/site-packages/semgrep/dependency_aware_rule.py", line 80, in generate_unreachable_sca_findings
    deps, _ = parse_lockfile_path(lockfile_path)
  File "/home/XXXXXXX/.local/lib/python3.9/site-packages/semdep/parse_lockfile.py", line 133, in parse_lockfile_path
    return (parse_lockfile(lockfile_path, manifest_path), None)
  File "/home/XXXXXXX/.local/lib/python3.9/site-packages/semdep/parsers/requirements.py", line 105, in parse_requirements
    deps = safe_path_parse(
  File "/home/XXXXXXX/.local/lib/python3.9/site-packages/semdep/parsers/util.py", line 302, in safe_path_parse
    text = path.read_text()
  File "/usr/lib/python3.9/pathlib.py", line 1256, in read_text
    return f.read()
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Please let me know if any additional details are required to help debug this bug.

**Comment by ievans** [comment]
@emjin related to https://github.com/returntocorp/semgrep/issues/4797?

**Comment by emjin** [comment]
SSC might need to do something similar to our unicode hack. cc @mmcqd

**Comment by realexcel2021** [comment]
I'm having this same issue, going back and forth in different referenced issues with out a straight forward cause or solution. I'm running semgrep in github actions

**Comment by rakeshmane** [comment]
@realexcel2021 if you want a quick solution then you can check this fix: https://github.com/semgrep/semgrep/pull/8421/files
