### ISSUE TITLE
Semgrep v1.46.0 `--sarif` flag error `Object of type ErrorType is not JSON serializable`

### ISSUE THREAD

**Issue by picatz** [semgrep/semgrep#9091]
**Describe the bug**
Semgrep v1.46.0 with the `--sarif` flag doesn't seem to work, and prints an error traceback for `Object of type ErrorType is not JSON serializable`. 

This seems to be related to internal error changes in [`cli/src/semgrep/error.py`](https://github.com/returntocorp/semgrep/commits/develop/cli/src/semgrep/error.py) (go to "Files changed" tab):
https://github.com/returntocorp/semgrep/compare/v1.45.0...v1.46.0#diff-3d41130ef524a38f08679ca77b0ddcb7f905c05fcc34f55e67736de01d49cfa6L66-L198

```console                              
┌──── ○○○ ────┐
│ Semgrep CLI │               
└─────────────┘               
                              
Scanning 2941 files (only git-tracked) with:
                                      
✔ Semgrep OSS
  ✔ Basic security coverage for first-party code vulnerabilities.
                                              
✘ Semgrep Code (SAST)
  ✘ Find and fix vulnerabilities in the code you write with advanced scanning and expert security rules.
                                                     
✘ Semgrep Supply Chain (SCA)
  ✘ Find and fix the reachable vulnerabilities in your OSS dependencies.
                                                                            
💎 Get started with all Semgrep products via `semgrep login`.
✨ Learn more at https://semgrep.dev/products/cloud-platform/.
                                                                            
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 100% 0:00:08                                                                                                                        
Object of type ErrorType is not JSON serializable
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/semgrep/1.46.0/libexec/lib/python3.11/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/opt/homebrew/Cellar/semgrep/1.46.0/libexec/lib/python3.11/site-packages/semgrep/commands/scan.py", line 653, in scan
    output_handler.output(
  File "/opt/homebrew/Cellar/semgrep/1.46.0/libexec/lib/python3.11/site-packages/semgrep/output.py", line 345, in output
    output = self._build_output()
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/semgrep/1.46.0/libexec/lib/python3.11/site-packages/semgrep/output.py", line 483, in _build_output
    return self.formatter.output(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/semgrep/1.46.0/libexec/lib/python3.11/site-packages/semgrep/formatter/base.py", line 28, in output
    return self.format(
           ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/semgrep/1.46.0/libexec/lib/python3.11/site-packages/semgrep/formatter/sarif.py", line 445, in format
    return json.dumps(output_dict, sort_keys=True, indent=2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ErrorType is not JSON serializable
```

**To Reproduce**

Using [`hashicorp/boundary@main`](https://github.com/hashicorp/boundary) as an example:

✅ Without the `--sarif` flag, the scan works:

```console
$ semgrep "--config=auto" "--use-git-ignore" "--exclude=.github/*" $PWD 
...
┌──────────────┐
│ Scan Summary │
└──────────────┘
Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Partially scanned: 23 files only partially analyzed due to parsing or internal Semgrep errors
  Scan skipped: 27 files matching --exclude patterns, 2 files larger than 1.0 MB, 775 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1101 rules on 2137 files: 67 findings.
```

❌ With the `--sarif` flag, the scan doesn't work:

```console
$ semgrep --sarif "--config=auto" "--use-git-ignore" "--exclude=.github/*" $PWD 
...
Object of type ErrorType is not JSON serializable
Traceback (most recent call last):
...
```

**Expected behavior**

SARIF should be printed with the `--sarif` flag, not an error traceback.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
We are currently pinned to v1.45.0, which works, but that's not ideal.

**Comment by TylerJang27** [comment]
Ran into the same problem running on this file:
```typescript
// element.ts
import React, { ReactElement } from "react";

export default function Bad(): ReactElement {
  return <div/>;
}
```

Issue only appears in 1.46.0, I ran `semgrep --config=auto --sarif --include=element.ts`
No issues are reported when running without `--sarif`.

**Comment by SPoint42** [comment]
I have something similar via --sarif export.... 

``` 
 File "/usr/local/lib/python3.11/site-packages/semgrep/formatter/sarif.py", line 435, in <listcomp>
    self._semgrep_error_to_sarif_notification(error)
  File "/usr/local/lib/python3.11/site-packages/semgrep/formatter/sarif.py", line 376, in _semgrep_error_to_sarif_notification
    level = error_to_sarif_level[error.level.value]
            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: Info_()
```

I ran inside a docker semgrep with the following arguments 

```
docker run -it -v $PWD:/srcs:rw semgrep -j 3 --metrics=off --exclude=/test/ --config /semgrep-rules --sarif -o semgrep-all.sarif .
```

**Comment by picatz** [comment]
Thanks for fixing this so quickly @aryx!

**Comment by cw-alexcroteau** [comment]
Sorry for bugging you on this @aryx , can we expect a patch release for this issue, or would it be fixed in the next minor release? Thanks!

**Comment by aryx** [comment]
We should release 1.47.0 tomorrow.

**Comment by picatz** [comment]
Perfect, thank you!

**Comment by jpastuszuk** [comment]
@aryx  - I have noticed, that despite the binary update, the docker latest image has not been updated yet.
This means that, any Github Actions running from official semgrep documentation still fails.

Would it be possible to push new version of Docker image?

**Comment by TylerJang27** [comment]
Likewise with [pypi](https://pypi.org/project/semgrep/) 🙏

**Comment by maxr-sg** [comment]
I get the error below when using the docker image with tag 1.47 
```
Run semgrep \
  semgrep \
    --sarif --output report.sarif \
    --metrics=off \
    --config="p/default" \
    --config="p/python" \
    --config="p/bandit" \ 
    --config="p/ci" \ 
    --config="p/secrets" \
    --config="r/contrib.dlint" \ 
    --config="r/python.requests"
  shell: sh -e {0}
  
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Error: Process completed with exit code [2]
```
my github action workflow:

```
semgrep:
    runs-on: ubuntu-latest
    container:
        image: returntocorp/semgrep:1.47
    steps:
      - name: clone application source code
        uses: actions/checkout@v3
      - name: full scan
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default" \
            --config="p/python" \
            --config="p/bandit" \ 
            --config="p/ci" \ 
            --config="p/secrets" \
            --config="r/contrib.dlint" \ 
            --config="r/python.requests"
      - if: ${{always()}}
        name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif

```

**Comment by sameersubudhi** [comment]
@maxr-sg I fixed mine by updating the run command to `semgrep ci` instead of just `semgrep`. You could try the same.

```
semgrep:
    runs-on: ubuntu-latest
    container:
        image: returntocorp/semgrep:1.47
    steps:
      - name: clone application source code
        uses: actions/checkout@v3
      - name: full scan
        run: |
          semgrep ci \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default" \
            --config="p/python" \
            --config="p/bandit" \ 
            --config="p/ci" \ 
            --config="p/secrets" \
            --config="r/contrib.dlint" \ 
            --config="r/python.requests"
      - if: ${{always()}}
        name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif
```

**Comment by aryx** [comment]
Should work now with 1.48.0. Let me know if you still have problems and we can reopen the issue
