### ISSUE TITLE
`semgrep --validate` applies metadata value type restrictions on custom fields

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#9365]
**Describe the bug**
We have a custom metadata field `risk_score`, that we want to use floats for. Running `semgrep --validate` returns a `ValueError: Invalid YAML tree structure (expected a list, dict, tree, int or str, found: ScalarFloat: 9.0` error. The rule is otherwise sound (to Semgrep)

**To Reproduce**
```
rules:
  - id: asdf
    mode: taint
    message: uh oh!
    severity: ERROR
    languages:
      - javascript
      - typescript
    metadata:
      risk_score: 9.0
    pattern-sources:
      - pattern: a
    pattern-sinks:
      - pattern: a
```
https://semgrep.dev/playground/s/7Kgpk for your convenience, but the float gets converted to an int when saving the rule, so be sure to unconvert it 

**Expected behavior**
`semgrep --validate` shouldn't throw errors here if the rule itself is valid

**Screenshots**
Full traceback:
```
❯ semgrep --validate --config a.yaml
Invalid YAML tree structure (expected a list, dict, tree, int or str, found: ScalarFloat: 9.0
Traceback (most recent call last):
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/commands/scan.py", line 567, in scan
    resolved_configs, config_errors = semgrep.config_resolver.get_config(
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/config_resolver.py", line 852, in get_config
    config, errors = Config.from_config_list(config_strs, project_url)
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/config_resolver.py", line 405, in from_config_list
    resolved_config = resolve_config(config, project_url)
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/config_resolver.py", line 338, in resolve_config
    config = parse_config_files(config_loader.load_config())
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/config_resolver.py", line 317, in parse_config_files
    config.update(parse_config_string(config_id, contents, filename))
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/config_resolver.py", line 716, in parse_config_string
    data = parse_config_preserve_spans(contents, filename)
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 453, in parse_config_preserve_spans
    validate_yaml(data)
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 562, in validate_yaml
    jsonschema.validate(data.unroll(), RuleSchema.get(), cls=Draft7Validator)
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 284, in unroll
    return {str(k.unroll()): v.unroll() for k, v in self.value.items()}
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 284, in <dictcomp>
    return {str(k.unroll()): v.unroll() for k, v in self.value.items()}
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 282, in unroll
    return [x.unroll() for x in self.value]
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 282, in <listcomp>
    return [x.unroll() for x in self.value]
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 284, in unroll
    return {str(k.unroll()): v.unroll() for k, v in self.value.items()}
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 284, in <dictcomp>
    return {str(k.unroll()): v.unroll() for k, v in self.value.items()}
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 284, in unroll
    return {str(k.unroll()): v.unroll() for k, v in self.value.items()}
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 284, in <dictcomp>
    return {str(k.unroll()): v.unroll() for k, v in self.value.items()}
  File "/Users/ennol/.asdf/installs/python/3.10.12/lib/python3.10/site-packages/semgrep/rule_lang.py", line 290, in unroll
    raise ValueError(
ValueError: Invalid YAML tree structure (expected a list, dict, tree, int or str, found: ScalarFloat: 9.0
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
CLI

**Use case**
We run `semgrep --validate` in our CI and are getting a lot of errors on that issue. This would make our CI less annoying

**Comment by aryx** [comment]
Hello enno :)
