### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git' 

### ISSUE THREAD

**Issue by mustafa-ans** [semgrep/semgrep#9768]
**Describe the bug**
I am getting this error message when I try to run the `semgrep ci` command in the root directory of my project. I am running semgrep on an Linux Ubuntu system and I installed semgrep via pip. My system also has git installed and it is added to path. 
The entire error message is as follows:
```
┌────────────────┐
│ Debugging Info │
└────────────────┘

  SCAN ENVIRONMENT
  versions    - semgrep 1.56.0 on python 3.10.12
  environment - running in environment git, triggering event is unknown

  CONNECTION
Traceback (most recent call last):
  File "/snap/semgrep/13/lib/python3.10/site-packages/semgrep/commands/ci.py", line 288, in ci
    project_meta: out.ProjectMetadata = metadata.to_project_metadata()
  File "/snap/semgrep/13/lib/python3.10/site-packages/semgrep/meta.py", line 195, in to_project_metadata
    commit_title = git_check_output(["git", "show", "-s", "--format=%B"])
  File "/snap/semgrep/13/lib/python3.10/site-packages/semgrep/git.py", line 45, in git_check_output
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
Could not start scan [Errno 2] No such file or directory: 'git'
There were errors during analysis but Semgrep will succeed because there were no blocking findings, use --no-suppress-errors if you want Semgrep to fail when there are errors.
```

**To Reproduce**
Ran the command `semgrep ci` in the project root directory

This is the project that I was running the command in: 
https://github.com/mustafa-ans/unit-testing-axum

**Expected behavior**
Scan of the project as per the functionality of semgrep

**Screenshots**
![image](https://github.com/semgrep/semgrep/assets/112391427/e402fd86-2eca-42f9-bc79-13642c785fdf)

**What is the priority of the bug to you?**
P0
- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
a local build

**Use case**
What will fixing this bug enable for you?
I will be able to use semgrep locally to scan my projects written in Rust

**Comment by ievans** [comment]
if you run `which git` what output do you get?

**Comment by mustafa-ans** [comment]
@ievans **thank you for replying**, here is the screenshot as requested

![image](https://github.com/semgrep/semgrep/assets/112391427/5c8e5e0c-0dd7-4624-9eb7-dcde97259679)

**Comment by ievans** [comment]
unfortunately I can't reproduce this. I'll ping the team to see if there are any ideas

**Comment by srvn-nm** [comment]
I have the same issue with [this project](https://github.com/snoopysecurity/Vulnerable-Code-Snippets)
and I have the same output when I run which git.
and I set semgrep up in wsl. 
Please help me fix it.

**Comment by mustafa-ans** [comment]
@srvn-nm I am running localized scans and it is working for me as opposed to the one they recommend in the docs. I have also setup semgrep in wsl. 

1. First cd into the root directory of the project or the module you want to run the scan in. 
2. Create a login token if haven't already by `semgrep login`
3. Click on the link to authorize the login session
4. Then run this command below:
`$ semgrep scan --config=auto `

@ievans I have been running localized scans ever since and for now it is sufficient for my limited use case.

**Comment by srvn-nm** [comment]
@ievans Thank you so much it worked.

**Comment by jonkiparsky** [comment]
Confirming the behavior described above. 

Doesn't work on my machine either.
